return {
    ["Activate Aimlock"] = {
        ["ar"] = "تفعيل قفل التصويب",
        ["de"] = "Zielerfassung aktivieren",
        ["en"] = "Activate Aimlock",
        ["es"] = "Activar Bloqueo de Mira",
        ["fr"] = "Activer le Verrouillage",
        ["pt"] = "Ativar Bloqueio de Mira",
        ["ru"] = "Активировать аимлок",
        ["tr"] = "Nişan Kilidini Etkinleştir",
    },
    ["Advanced Configurations"] = {
        ["ar"] = "التكوينات المتقدمة",
        ["de"] = "Erweiterte Konfigurationen",
        ["en"] = "Advanced Configurations",
        ["es"] = "Configuraciones Avanzadas",
        ["fr"] = "Configurations Avancées",
        ["pt"] = "Configurações Avançadas",
        ["ru"] = "Расширенные настройки",
        ["tr"] = "Gelişmiş Yapılandırmalar",
    },
    ["Aim Configurations"] = {
        ["ar"] = "تكوينات التصويب",
        ["de"] = "Zieleinstellungen",
        ["en"] = "Aim Configurations",
        ["es"] = "Configuraciones de Apuntado",
        ["fr"] = "Configurations de Visée",
        ["pt"] = "Configurações de Mira",
        ["ru"] = "Настройки прицеливания",
        ["tr"] = "Nişan Ayarları",
    },
    ["Aim Part"] = {
        ["ar"] = "عضو التصويب",
        ["de"] = "Zielteil",
        ["en"] = "Aim Part",
        ["es"] = "Parte de Apuntado",
        ["fr"] = "Partie de Visée",
        ["pt"] = "Parte de Mira",
        ["ru"] = "Часть тела",
        ["tr"] = "Nişan Bölgesi",
    },
    ["AimLock"] = {
        ["ar"] = "قفل التصويب",
        ["de"] = "Zielerfassung",
        ["en"] = "AimLock",
        ["es"] = "Bloqueo de Mira",
        ["fr"] = "Verrouillage de Visée",
        ["pt"] = "Bloqueio de Mira",
        ["ru"] = "Аимлок",
        ["tr"] = "Nişan Kilidi",
    },
    ["Aimlock Certain Player"] = {
        ["ar"] = "تصويب على لاعب معين",
        ["de"] = "Bestimmten Spieler erfassen",
        ["en"] = "Aimlock Certain Player",
        ["es"] = "Apuntar a un Jugador Específico",
        ["fr"] = "Viser un Joueur Spécifique",
        ["pt"] = "Mirar em Jogador Específico",
        ["ru"] = "Аимлок на определенного игрока",
        ["tr"] = "Belirli Oyuncuya Nişan Al",
    },
    ["Aimlock Offset (X)"] = {
        ["ar"] = "إزاحة التصويب الأفقية (X)",
        ["de"] = "Zielerfassungs-Offset (X)",
        ["en"] = "Aimlock Offset (X)",
        ["es"] = "Desviación de Apuntado (X)",
        ["fr":] = "Décalage de la Visée (X)",
        ["pt"] = "Desvio de Mira (X)",
        ["ru"] = "Смещение аимлока (X)",
        ["tr"] = "Nişan Sapması (X)",
    },
    ["Aimlock Offset (Y)"] = {
        ["ar"] = "إزاحة التصويب الرأسية (Y)",
        ["de"] = "Zielerfassungs-Offset (Y)",
        ["en"] = "Aimlock Offset (Y)",
        ["es"] = "Desviación de Apuntado (Y)",
        ["fr"] = "Décalage de la Visée (Y)",
        ["pt"] = "Desvio de Mira (Y)",
        ["ru"] = "Смещение аимлока (Y)",
        ["tr"] = "Nişan Sapması (Y)",
    },
    ["Aimlock Type"] = {
        ["ar"] = "نوع قفل التصويب",
        ["de"] = "Zielerfassungsart",
        ["en"] = "Aimlock Type",
        ["es"] = "Tipo de Bloqueo de Mira",
        ["fr"] = "Type de Verrouillage",
        ["pt"] = "Tipo de Bloqueio de Mira",
        ["ru"] = "Тип аимлока",
        ["tr"] = "Nişan Kilidi Türü",
    },
    ["Apply Custom SFX"] = {
        ["ar"] = "تطبيق الأصوات المخصصة",
        ["de"] = "SFX anwenden",
        ["en"] = "Apply Custom SFX",
        ["es"] = "Aplicar SFX Personalizado",
        ["fr"] = "Appliquer les SFX",
        ["pt"] = "Aplicar SFX Personalizado",
        ["ru"] = "Применить кастомные звуки",
        ["tr"] = "Özel SFX Uygula",
    },
    ["Auto Apply Custom SFX"] = {
        ["ar"] = "تطبيق تلقائي للأصوات المخصصة",
        ["de"] = "SFX automatisch anwenden",
        ["en"] = "Auto Apply Custom SFX",
        ["es"] = "Auto Aplicar SFX Personalizado",
        ["fr"] = "Appliquer les SFX Auto",
        ["pt"] = "Auto Aplicar SFX",
        ["ru"] = "Авто-применение звуков",
        ["tr"] = "Özel SFX Otomatik Uygula",
    },
    ["Auto Apply Delay"] = {
        ["ar"] = "تأخير التطبيق التلقائي للأصوات",
        ["de"] = "Auto-Anwendung Verzögerung",
        ["en"] = "Auto Apply Delay",
        ["es"] = "Retraso de Auto Aplicación",
        ["fr"] = "Délai d'Application Auto",
        ["pt"] = "Atraso de Auto Aplicação",
        ["ru"] = "Задержка авто-применения",
        ["tr"] = "Otomatik Uygulama Gecikmesi",
    },
    ["Auto Play"] = {
        ["ar"] = "لعب تلقائي",
        ["de"] = "Auto-Spiel",
        ["en"] = "Auto Play",
        ["es"] = "Juego Automático",
        ["fr"] = "Auto Play",
        ["pt"] = "Auto Play",
        ["ru"] = "Авто-игра",
        ["tr"] = "Otomatik Oyna",
    },
    ["Auto Respawn"] = {
        ["ar"] = "إعادة رسبون تلقائي",
        ["de"] = "Auto-Wiederbelebung",
        ["en"] = "Auto Respawn",
        ["es"] = "Auto Reaparecer",
        ["fr"] = "Réapparition Auto",
        ["pt"] = "Auto Reaparecer",
        ["ru"] = "Авто-возрождение",
        ["tr"] = "Otomatik Yeniden Doğma",
    },
    ["Auto Respawn Delay"] = {
        ["ar"] = "تأخير الرسبون التلقائي",
        ["de"] = "Wiederbelebungs-Verzögerung",
        ["en"] = "Auto Respawn Delay",
        ["es"] = "Retraso de Auto Reaparecer",
        ["fr"] = "Délai de Réapparition",
        ["pt"] = "Atraso do Auto Reaparecer",
        ["ru"] = "Задержка авто-возрождения",
        ["tr"] = "Yeniden Doğma Gecikmesi",
    },
    ["Auto-Fire"] = {
        ["ar"] = "إطلق تلقائي",
        ["de"] = "Automatisches Feuern",
        ["en"] = "Auto-Fire",
        ["es"] = "Disparo Automático",
        ["fr"] = "Tir Automatique",
        ["pt"] = "Disparo Automático",
        ["ru"] = "Авто-выстрел",
        ["tr"] = "Otomatik Ateş",
    },
    ["Auto-Fire Delay (W.I.P)"] = {
        ["ar"] = "تأخير الإطلاق التلقائي (قيد العمل)",
        ["de"] = "Auto-Feuer Verzögerung (In Arbeit)",
        ["en"] = "Auto-Fire Delay (W.I.P)",
        ["es"] = "Retraso de Disparo Automático (WIP)",
        ["fr"] = "Délai de Tir Auto (En cours)",
        ["pt"] = "Atraso do Disparo Automático (WIP)",
        ["ru"] = "Задержка авто-выстрела (в разработке)",
        ["tr"] = "Otomatik Ateş Gecikmesi (Yapım Aşamasında)",
    },
    ["Auto-Fire Shoot Delay (W.I.P)"] = {
        ["ar"] = "تأخير ضربة الإطلاق (قيد العمل)",
        ["de"] = "Schussverzögerung (In Arbeit)",
        ["en"] = "Auto-Fire Shoot Delay (W.I.P)",
        ["es"] = "Retraso al Disparar (WIP)",
        ["fr"] = "Délai de Frappe Auto (En cours)",
        ["pt"] = "Atraso de Tiro (WIP)",
        ["ru"] = "Задержка выстрела (в разработке)",
        ["tr"] = "Ateş Etme Gecikmesi (Yapım Aşamasında)",
    },
    ["Bullet Trails"] = {
        ["ar"] = "مسارات الرصاص",
        ["de"] = "Kugelspuren",
        ["en"] = "Bullet Trails",
        ["es"] = "Estelas de Bala",
        ["fr"] = "Traînées de Balles",
        ["pt"] = "Rastros de Bala",
        ["ru"] = "Следы от пуль",
        ["tr"] = "Mermi İzleri",
    },
    ["Bunny Hop"] = {
        ["ar"] = "قفز الأرنب (Bunny Hop)",
        ["de"] = "Bunny Hop",
        ["en"] = "Bunny Hop",
        ["es"] = "Salto de Conejo",
        ["fr"] = "Bunny Hop",
        ["pt"] = "Bunny Hop",
        ["ru"] = "Банни-хоп",
        ["tr"] = "Tavşan Zıplaması",
    },
    ["Bunny Hop Delay"] = {
        ["ar"] = "تأخير قفز الأرنب",
        ["de"] = "Bunny Hop Verzögerung",
        ["en"] = "Bunny Hop Delay",
        ["es"] = "Retraso de Bunny Hop",
        ["fr"] = "Délai de Bunny Hop",
        ["pt"] = "Atraso do Bunny Hop",
        ["ru"] = "Задержка банни-хопа",
        ["tr"] = "Tavşan Zıplama Gecikmesi",
    },
    ["Change Material To Neon"] = {
        ["ar"] = "تحويل خام السلاح إلى نيون مضيء",
        ["de"] = "Material in Neon ändern",
        ["en"] = "Change Material To Neon",
        ["es"] = "Cambiar Material a Neón",
        ["fr"] = "Changer Matériau en Néon",
        ["pt"] = "Mudar Material para Neon",
        ["ru"] = "Сделать материал неоновым",
        ["tr"] = "Malzemeyi Neon Yap",
    },
    ["Character"] = {
        ["ar"] = "الشخصية",
        ["de"] = "Charakter",
        ["en"] = "Character",
        ["es"] = "Personaje",
        ["fr"] = "Personnage",
        ["pt"] = "Personagem",
        ["ru"] = "Персонаж",
        ["tr"] = "Karakter",
    },
    ["Circle"] = {
        ["ar"] = "الدائرة",
        ["de"] = "Kreis",
        ["en"] = "Circle",
        ["es"] = "Círculo",
        ["fr"] = "Cercle",
        ["pt"] = "Círculo",
        ["ru"] = "Круг",
        ["tr"] = "Daire",
    },
    ["Combat Features"] = {
        ["ar"] = "ميزات القتال",
        ["de"] = "Kampffunktionen",
        ["en"] = "Combat Features",
        ["es"] = "Funciones de Combate",
        ["fr"] = "Fonctionnalités de Combat",
        ["pt"] = "Recursos de Combate",
        ["ru"] = "Боевые функции",
        ["tr"] = "Savaş Özellikleri",
    },
    ["Configurations"] = {
        ["ar"] = "التكوينات",
        ["de"] = "Konfigurationen",
        ["en"] = "Configurations",
        ["es"] = "Configuraciones",
        ["fr"] = "Configurations",
        ["pt"] = "Configurações",
        ["ru"] = "Конфигурации",
        ["tr"] = "Yapılandırmalar",
    },
    ["Crates"] = {
        ["ar"] = "الصناديق",
        ["de"] = "Kisten",
        ["en"] = "Crates",
        ["es"] = "Cajas",
        ["fr"] = "Caisses",
        ["pt"] = "Caixas",
        ["ru"] = "Ящики",
        ["tr"] = "Sandıklar",
    },
    ["Critical SFX"] = {
        ["ar"] = "صوت الضربة الحرجة (Critical)",
        ["de"] = "Kritischer SFX",
        ["en"] = "Critical SFX",
        ["es"] = "SFX Crítico",
        ["fr"] = "SFX Critique",
        ["pt"] = "SFX Crítico",
        ["ru"] = "Звук крита",
        ["tr"] = "Kritik SFX",
    },
    ["Custom SFX"] = {
        ["ar"] = "مؤثرات صوتية مخصصة",
        ["de"] = "Benutzerdefinierte SFX",
        ["en"] = "Custom SFX",
        ["es"] = "SFX Personalizado",
        ["fr"] = "Effets Sonores Personnalisés",
        ["pt"] = "Efectos de Som Personalizados",
        ["ru"] = "Кастомные звуки",
        ["tr"] = "Özel SFX",
    },
    ["Destroy Gui"] = {
        ["ar"] = "إغلاق السكربت كلياً",
        ["de"] = "Gui zerstören",
        ["en"] = "Destroy Gui",
        ["es"] = "Cerrar Script",
        ["fr"] = "Fermer le Script",
        ["pt"] = "Fechar Script",
        ["ru"] = "Уничтожить чит",
        ["tr"] = "Arayüzü Kapat",
    },
    ["Discord Server"] = {
        ["ar"] = "سيرفر ديسكورد",
        ["de"] = "Discord Server",
        ["en"] = "Discord Server",
        ["es"] = "Servidor de Discord",
        ["fr"] = "Serveur Discord",
        ["pt"] = "Servidor do Discord",
        ["ru"] = "Дискорд Сервер",
        ["tr"] = "Discord Sunucusu",
    },
    ["ESP"] = {
        ["ar"] = "كشف الأماكن (ESP)",
        ["de"] = "ESP",
        ["en"] = "ESP",
        ["es"] = "ESP",
        ["fr"] = "ESP",
        ["pt"] = "ESP",
        ["ru"] = "ЕСП",
        ["tr"] = "ESP",
    },
    ["ESP Color"] = {
        ["ar"] = "لون الكشف",
        ["de"] = "ESP-Farbe",
        ["en"] = "ESP Color",
        ["es"] = "Color de ESP",
        ["fr"] = "Couleur de l'ESP",
        ["pt"] = "Cor do ESP",
        ["ru"] = "Цвет ЕСП",
        ["tr"] = "ESP Rengi",
    },
    ["ESP Size"] = {
        ["ar"] = "حجم الكشف",
        ["de"] = "ESP-Größe",
        ["en"] = "ESP Size",
        ["es"] = "Tamaño de ESP",
        ["fr"] = "Taille de l'ESP",
        ["pt"] = "Tamanho do ESP",
        ["ru"] = "Размер ЕСП",
        ["tr"] = "ESP Boyutu",
    },
    ["Enable FOV"] = {
        ["ar"] = "تفعيل دائرة الرؤية",
        ["de"] = "FOV aktivieren",
        ["en"] = "Enable FOV",
        ["es"] = "Activar FOV",
        ["fr"] = "Activer le FOV",
        ["pt"] = "Ativar FOV",
        ["ru"] = "Включить FOV",
        ["tr"] = "Görüş Alanını Etkinleştir",
    },
    ["FOV Color"] = {
        ["ar"] = "لون دائرة الرؤية",
        ["de"] = "FOV-Farbe",
        ["en"] = "FOV Color",
        ["es"] = "Color de FOV",
        ["fr"] = "Couleur du FOV",
        ["pt"] = "Cor do FOV",
        ["ru"] = "Цвет FOV",
        ["tr"] = "Görüş Alanı Rengi",
    },
    ["FOV Lock Distance (Studs)"] = {
        ["ar"] = "مسافة قفل الرؤية",
        ["de"] = "FOV-Sperrabstand",
        ["en"] = "FOV Lock Distance (Studs)",
        ["es"] = "Distancia de Bloqueo de FOV",
        ["fr"] = "Distance de Verrouillage du FOV",
        ["pt"] = "Distância de Bloqueio de FOV",
        ["ru"] = "Дистанция блокировки FOV",
        ["tr"] = "Görüş Alanı Kilitleme Mesafesi",
    },
    ["FOV Size"] = {
        ["ar"] = "حجم دائرة الرؤية",
        ["de"] = "FOV-Größe",
        ["en"] = "FOV Size",
        ["es"] = "Tamaño de FOV",
        ["fr"] = "Taille du FOV",
        ["pt"] = "Tamanho do FOV",
        ["ru"] = "Размер FOV",
        ["tr"] = "Görüş Alanı Boyutu",
    },
    ["FOV Stroke Thickness"] = {
        ["ar"] = "سمك إطار دائرة الرؤية",
        ["de"] = "FOV-Rahmenstärke",
        ["en"] = "FOV Stroke Thickness",
        ["es"] = "Grosor del Borde de FOV",
        ["fr"] = "Épaisseur du Bord du FOV",
        ["pt"] = "Espessura da Borda do FOV",
        ["ru"] = "Толщина границы FOV",
        ["tr"] = "Görüş Alanı Çerçeve Kalınlığı",
    },
    ["FPS Boost"] = {
        ["ar"] = "تحسين الفريمات (FPS Boost)",
        ["de"] = "FPS-Boost",
        ["en"] = "FPS Boost",
        ["es"] = "Aumento de FPS",
        ["fr"] = "Boost d'FPS",
        ["pt"] = "Aumento de FPS",
        ["ru"] = "Буст ФПС",
        ["tr"] = "FPS Arttırıcı",
    },
    ["Field Of View"] = {
        ["ar"] = "مجال الرؤية (FOV)",
        ["de"] = "Sichtfeld",
        ["en"] = "Field Of View",
        ["es"] = "Campo de Visión",
        ["fr"] = "Champ de Vision",
        ["pt"] = "Campo de Visão",
        ["ru"] = "Поле зрения",
        ["tr"] = "Görüş Alanı",
    },
    ["Fill Color"] = {
        ["ar"] = "لون التعبئة",
        ["de"] = "Füllfarbe",
        ["en"] = "Fill Color",
        ["es"] = "Color de Relleno",
        ["fr"] = "Couleur de Remplissage",
        ["pt"] = "Cor de Preenchimento",
        ["ru"] = "Цвет заливки",
        ["tr"] = "Dolgu Rengi",
    },
    ["Full Bright"] = {
        ["ar"] = "إضاءة كاملة",
        ["de"] = "Volle Helligkeit",
        ["en"] = "Full Bright",
        ["es"] = "Brillo Máximo",
        ["fr"] = "Lumière Totale",
        ["pt"] = "Brilho Total",
        ["ru"] = "Полная яркость",
        ["tr"] = "Tam Parlaklık",
    },
    ["Fun"] = {
        ["ar"] = "المتعة/التسلية",
        ["de"] = "Spaß",
        ["en"] = "Fun",
        ["es"] = "Diversión",
        ["fr"] = "Divertissement",
        ["pt"] = "Diversão",
        ["ru"] = "Развлечения",
        ["tr"] = "Eğlence",
    },
    ["Game"] = {
        ["ar"] = "اللعبة",
        ["de"] = "Spiel",
        ["en"] = "Game",
        ["es"] = "Juego",
        ["fr"] = "Jeu",
        ["pt"] = "Jogo",
        ["ru"] = "Игра",
        ["tr"] = "Oyun",
    },
    ["Gun Crate Count To Open"] = {
        ["ar"] = "عدد صناديق المسدسات للفتح",
        ["de"] = "Anzahl zu öffnender Pistolenkisten",
        ["en"] = "Gun Crate Count To Open",
        ["es"] = "Cantidad de Cajas de Pistolas a Abrir",
        ["fr"] = "Nombre de Caisses Pistolet à Ouvrir",
        ["pt"] = "Quantidade de Caixas de Armas",
        ["ru"] = "Количество открываемых ящиков пистолетов",
        ["tr"] = "Açılacak Silah Sandığı Sayısı",
    },
    ["Hit Color"] = {
        ["ar"] = "لون الإصابة",
        ["de"] = "Treffer-Farbe",
        ["en"] = "Hit Color",
        ["es"] = "Color de Impacto",
        ["fr"] = "Couleur de Touche",
        ["pt"] = "Cor de Acerto",
        ["ru"] = "Цвет попадания",
        ["tr"] = "Vurma Rengi",
    },
    ["Hit SFX"] = {
        ["ar"] = "صوت الإصابة",
        ["de"] = "Treffer-SFX",
        ["en"] = "Hit SFX",
        ["es"] = "SFX de Impacto",
        ["fr"] = "SFX de Touche",
        ["pt"] = "SFX de Acerto",
        ["ru"] = "Звук попадания",
        ["tr"] = "Vurma SFX",
    },
    ["Ignore Lobby"] = {
        ["ar"] = "تجاهل اللوبي",
        ["de"] = "Lobby ignorieren",
        ["en"] = "Ignore Lobby",
        ["es"] = "Ignorar Lobby",
        ["fr"] = "Ignorer le Lobby",
        ["pt"] = "Ignorar Lobby",
        ["ru"] = "Игнорировать лобби",
        ["tr"] = "Lobiyi Yoksay",
    },
    ["Ignore Players"] = {
        ["ar"] = "تجاهل اللاعبين",
        ["de"] = "Spieler ignorieren",
        ["en"] = "Ignore Players",
        ["es"] = "Ignorar Jugadores",
        ["fr"] = "Ignorer les Joueurs",
        ["pt"] = "Ignorar Jogadores",
        ["ru"] = "Игнорировать игроков",
        ["tr"] = "Oyuncuları Yoksay",
    },
    ["Ignore Shielded"] = {
        ["ar"] = "تجاهل المحميين",
        ["de"] = "Geschützte ignorieren",
        ["en"] = "Ignore Shielded",
        ["es"] = "Ignorar Protegidos",
        ["fr"] = "Ignorer les Protégés",
        ["pt"] = "Ignorar Protegidos",
        ["ru"] = "Игнорировать со щитом",
        ["tr"] = "Kalkanlıları Yoksay",
    },
    ["Knife Crate Count To Open"] = {
        ["ar"] = "عدد صناديق السكاكين للفتح",
        ["de"] = "Anzahl zu öffnender Messerkisten",
        ["en"] = "Knife Crate Count To Open",
        ["es"] = "Cantidad de Cajas de Cuchillos a Abrir",
        ["fr"] = "Nombre de Caisses Couteau à Ouvrir",
        ["pt"] = "Quantidade de Caixas de Facas",
        ["ru"] = "Количество открываемых ящиков ножей",
        ["tr"] = "Açılacak Bıçak Sandığı Sayısı",
    },
    ["Language"] = {
        ["ar"] = "اللغة",
        ["de"] = "Sprache",
        ["en"] = "Language",
        ["es"] = "Idioma",
        ["fr"] = "Langue",
        ["pt"] = "Idioma",
        ["ru"] = "Язык",
        ["tr"] = "Dil",
    },
    ["Link Copied"] = {
        ["ar"] = "تم نسخ الرابط",
        ["de"] = "Link kopiert",
        ["en"] = "Link Copied",
        ["es"] = "Enlace Copiado",
        ["fr"] = "Lien Copié",
        ["pt"] = "Link Copiado",
        ["ru"] = "Ссылка скопирована",
        ["tr"] = "Bağlantı Kopyalandı",
    },
    ["Lobby"] = {
        ["ar"] = "اللوبي",
        ["de"] = "Lobby",
        ["en"] = "Lobby",
        ["es"] = "Lobby",
        ["fr"] = "Lobby",
        ["pt"] = "Lobby",
        ["ru"] = "Лобби",
        ["tr"] = "Lobi",
    },
    ["Mass Open Gun Crate"] = {
        ["ar"] = "فتح صناديق المسدسات بالجملة",
        ["de"] = "Pistolen-Kisten massenhaft öffnen",
        ["en"] = "Mass Open Gun Crate",
        ["es"] = "Abrir Cajas de Pistolas Masivamente",
        ["fr"] = "Ouvrir Caisses Pistolet en Masse",
        ["pt"] = "Abrir Caixas de Armas em Massa",
        ["ru"] = "Массовое открытие ящиков с пистолетами",
        ["tr"] = "Toplu Silah Sandığı Aç",
    },
    ["Mass Open Knife Crate"] = {
        ["ar"] = "فتح صناديق السكاكين بالجملة",
        ["de"] = "Messer-Kisten massenhaft öffnen",
        ["en"] = "Mass Open Knife Crate",
        ["es"] = "Abrir Cajas de Cuchillos Masivamente",
        ["fr"] = "Ouvrir Caisses Couteau en Masse",
        ["pt"] = "Abrir Caixas de Facas em Massa",
        ["ru"] = "Массовое открытие ящиков с ножами",
        ["tr"] = "Toplu Bıçak Sandığı Aç",
    },
    ["Menu"] = {
        ["ar"] = "القائمة",
        ["de"] = "Menü",
        ["en"] = "Menu",
        ["es"] = "Menú",
        ["fr"] = "Menu",
        ["pt"] = "Menu",
        ["ru"] = "Меню",
        ["tr"] = "Menü",
    },
    ["Miss Color"] = {
        ["ar"] = "لون الخطأ (عدم الإصابة)",
        ["de"] = "Fehlschuss-Farbe",
        ["en"] = "Miss Color",
        ["es"] = "Color de Fallo",
        ["fr"] = "Couleur de Manqué",
        ["pt"] = "Cor de Erro",
        ["ru"] = "Цвет промаха",
        ["tr"] = "Kaçırma Rengi",
    },
    ["Nearest Mouse Lock Distance (Studs)"] = {
        ["ar"] = "أقصى مسافة قفل للماوس (بالوحدات)",
        ["de"] = "Sperrabstand zur nächsten Maus (Studs)",
        ["en"] = "Nearest Mouse Lock Distance (Studs)",
        ["es"] = "Distancia de Bloqueo al Mouse más Cercano",
        ["fr"] = "Distance de Verrouillage de la Souris Proche",
        ["pt"] = "Distância de Bloqueio do Mouse Mais Próximo",
        ["ru"] = "Дистанция захвата мыши (в штудах)",
        ["tr"] = "En Yakın Fare Kilitleme Mesafesi (Birim)",
    },
    ["Nearest Player Lock Distance (Studs)"] = {
        ["ar"] = "أقصى مسافة قفل للاعب (بالوحدات)",
        ["de"] = "Sperrabstand zum nächsten Spieler (Studs)",
        ["en"] = "Nearest Player Lock Distance (Studs)",
        ["es"] = "Distancia de Bloqueo al Jugador más Cercano",
        ["fr"] = "Distance de Verrouillage du Joueur Proche",
        ["pt"] = "Distância de Bloqueio do Jogador Mais Próximo",
        ["ru"] = "Дистанция захвата игрока (в штудах)",
        ["tr"] = "En Yakın Oyuncu Kilitleme Mesafesi (Birim)",
    },
    ["No Fog"] = {
        ["ar"] = "إزالة الضباب",
        ["de"] = "Kein Nebel",
        ["en"] = "No Fog",
        ["es"] = "Sin Niebla",
        ["fr"] = "Sans Brouillard",
        ["pt"] = "Sem Névoa",
        ["ru"] = "Без тумана",
        ["tr"] = "Sis Yok",
    },
    ["No Velocity"] = {
        ["ar"] = "إلغاء قوة الدفع",
        ["de"] = "Keine Impulsgeschwindigkeit",
        ["en"] = "No Velocity",
        ["es"] = "Sin Velocidad",
        ["fr"] = "Sans Vélocité",
        ["pt"] = "Sem Velocidade",
        ["ru"] = "Без импульса",
        ["tr"] = "İtme Gücünü Kapat",
    },
    ["Other"] = {
        ["ar"] = "أخرى",
        ["de"] = "Andere",
        ["en"] = "Other",
        ["es"] = "Otros",
        ["fr"] = "Autre",
        ["pt"] = "Outros",
        ["ru"] = "Другое",
        ["tr"] = "Diğer",
    },
    ["Outline"] = {
        ["ar"] = "الحد الخارجي",
        ["de"] = "Umriss",
        ["en"] = "Outline",
        ["es"] = "Contorno",
        ["fr"] = "Contour",
        ["pt"] = "Contorno",
        ["ru"] = "Обводка",
        ["tr"] = "Çerçeve",
    },
    ["Outline Color"] = {
        ["ar"] = "لون الحد الخارجي",
        ["de"] = "Umrissfarbe",
        ["en"] = "Outline Color",
        ["es"] = "Color de Contorno",
        ["fr"] = "Couleur du Contour",
        ["pt"] = "Cor do Contorno",
        ["ru"] = "Цвет обводки",
        ["tr"] = "Çerçeve Rengi",
    },
    ["Outline Fill Transparency"] = {
        ["ar"] = "شفافية تعبئة الحد",
        ["de"] = "Fülltransparenz",
        ["en"] = "Outline Fill Transparency",
        ["es"] = "Transparencia de Relleno",
        ["fr"] = "Transparence du Remplissage",
        ["pt"] = "Transparência de Preenchimento",
        ["ru"] = "Прозрачность заливки",
        ["tr"] = "Çerçeve Dolgu Şeffaflığı",
    },
    ["Outline Transparency"] = {
        ["ar"] = "شفافية الحد الخارجي",
        ["de"] = "Umrisstransparenz",
        ["en"] = "Outline Transparency",
        ["es"] = "Transparencia de Contorno",
        ["fr"] = "Transparence du Contour",
        ["pt"] = "Transparência do Contorno",
        ["ru"] = "Прозрачность обводки",
        ["tr"] = "Çerçeve Şeffaflığı",
    },
    ["Performance"] = {
        ["ar"] = "الأداء",
        ["de"] = "Leistung",
        ["en"] = "Performance",
        ["es"] = "Rendimiento",
        ["fr"] = "Performance",
        ["pt"] = "Desempenho",
        ["ru"] = "Производительность",
        ["tr"] = "Performans",
    },
    ["Play"] = {
        ["ar"] = "لعب",
        ["de"] = "Spielen",
        ["en"] = "Play",
        ["es"] = "Jugar",
        ["fr"] = "Jouer",
        ["pt"] = "Jogar",
        ["ru"] = "Играть",
        ["tr"] = "Oyna",
    },
    ["Players Count: "] = {
        ["ar"] = "عدد اللاعبين: ",
        ["de"] = "Spieleranzahl: ",
        ["en"] = "Players Count: ",
        ["es"] = "Jugadores: ",
        ["fr"] = "Joueurs: ",
        ["pt"] = "Jogadores: ",
        ["ru"] = "Игроков: ",
        ["tr"] = "Oyuncu Sayısı: ",
    },
    ["Prioritize Players"] = {
        ["ar"] = "تفضل اللاعبين",
        ["de"] = "Spieler priorisieren",
        ["en"] = "Prioritize Players",
        ["es"] = "Priorizar Jugadores",
        ["fr"] = "Prioriser les Joueurs",
        ["pt"] = "Priorizar Jogadores",
        ["ru"] = "Приоритет игроков",
        ["tr"] = "Oyunculara Öncelik Ver",
    },
    ["RGB ASync"] = {
        ["ar"] = "تزامن ألوان RGB غير متزامن",
        ["de"] = "RGB Asynchron",
        ["en"] = "RGB ASync",
        ["es"] = "RGB Asincrónico",
        ["fr"] = "RGB Asynchrone",
        ["pt"] = "RGB Assíncrono",
        ["ru"] = "RGB Асинхронно",
        ["tr"] = "RGB Asenkron",
    },
    ["RGB ASync Spectrum Mode"] = {
        ["ar"] = "نمط طيف الـ RGB غير المتزامن",
        ["de"] = "RGB Asynchron-Spektrummodus",
        ["en"] = "RGB ASync Spectrum Mode",
        ["es"] = "Modo Espectro de RGB Asincrónico",
        ["fr"] = "Mode Spectre RGB Asynchrone",
        ["pt"] = "Modo Espectro RGB Assíncrono",
        ["ru"] = "Режим спектра RGB Асинхронно",
        ["tr"] = "RGB Asenkron Spektrum Modu",
    },
    ["RGB ASync Speed"] = {
        ["ar"] = "سرعة الـ RGB غير المتزامن",
        ["de"] = "RGB Asynchrongeschwindigkeit",
        ["en"] = "RGB ASync Speed",
        ["es"] = "Velocidad de RGB Asincrónico",
        ["fr"] = "Vitesse RGB Asynchrone",
        ["pt"] = "Velocidade RGB Assíncrona",
        ["ru"] = "Скорость RGB Асинхронно",
        ["tr"] = "RGB Asenkron Hızı",
    },
    ["RGB Gun/Knife"] = {
        ["ar"] = "سلاح RGB ملون",
        ["de"] = "RGB Waffe/Messer",
        ["en"] = "RGB Gun/Knife",
        ["es"] = "Arma/Cuchillo RGB",
        ["fr"] = "Arme/Couteau RGB",
        ["pt"] = "Arma/Faca RGB",
        ["ru"] = "RGB Оружие/Нож",
        ["tr"] = "RGB Silah/Bıçak",
    },
    ["RGB Re-Apply Speed"] = {
        ["ar"] = "سرعة إعادة تطبيق الـ RGB",
        ["de"] = "RGB-Reaktivierungsgeschwindigkeit",
        ["en"] = "RGB Re-Apply Speed",
        ["es"] = "Velocidad Reaplicación RGB",
        ["fr"] = "Vitesse Réapplication RGB",
        ["pt"] = "Velocidade Reaplicação RGB",
        ["ru"] = "Задержка обновления RGB",
        ["tr"] = "RGB Yenileme Hızı",
    },
    ["RGB Speed (Local)"] = {
        ["ar"] = "سرعة الـ RGB (محلي)",
        ["de"] = "RGB-Geschwindigkeit (Lokal)",
        ["en"] = "RGB Speed (Local)",
        ["es"] = "Velocidad RGB (Local)",
        ["fr"] = "Vitesse RGB (Local)",
        ["pt"] = "Velocidade RGB (Local)",
        ["ru"] = "Скорость RGB (локально)",
        ["tr"] = "RGB Hızı (Yerel)",
    },
    ["RGB Type"] = {
        ["ar"] = "نوع تأثير الـ RGB",
        ["de"] = "RGB-Typ",
        ["en"] = "RGB Type",
        ["es"] = "Tipo de RGB",
        ["fr"] = "Type de RGB",
        ["pt"] = "Tipo de RGB",
        ["ru"] = "Тип RGB",
        ["tr"] = "RGB Türü",
    },
    ["Rainbow ESP"] = {
        ["ar"] = "كشف قوس قزح",
        ["de"] = "Regenbogen-ESP",
        ["en"] = "Rainbow ESP",
        ["es"] = "ESP Arcoiris",
        ["fr"] = "ESP Arc-en-ciel",
        ["pt"] = "ESP Arco-íris",
        ["ru"] = "Радужный ЕСП",
        ["tr"] = "Gökkuşağı ESP",
    },
    ["Rainbow FOV"] = {
        ["ar"] = "دائرة رؤية قوس قزح",
        ["de"] = "Regenbogen-FOV",
        ["en"] = "Rainbow FOV",
        ["es"] = "FOV Arcoiris",
        ["fr"] = "FOV Arc-en-ciel",
        ["pt"] = "FOV Arco-íris",
        ["ru"] = "Радужный FOV",
        ["tr"] = "Gökkuşağı Görüş Alanı",
    },
    ["Rainbow Outline"] = {
        ["ar"] = "حد خارجي قوس قزح",
        ["de"] = "Regenbogen-Umriss",
        ["en"] = "Rainbow Outline",
        ["es"] = "Contorno Arcoiris",
        ["fr"] = "Contour Arc-en-ciel",
        ["pt"] = "Contorno Arco-íris",
        ["ru"] = "Радужная обводка",
        ["tr"] = "Gökkuşağı Çerçeve",
    },
    ["Rainbow Speed"] = {
        ["ar"] = "سرعة قوس قزح",
        ["de"] = "Regenbongengeschwindigkeit",
        ["en"] = "Rainbow Speed",
        ["es"] = "Velocidad de Arcoiris",
        ["fr"] = "Vitesse de l'Arc-en-ciel",
        ["pt"] = "Velocidade do Arco-íris",
        ["ru"] = "Скорость радуги",
        ["tr"] = "Gökkuşağı Hızı",
    },
    ["Rainbow Tracers"] = {
        ["ar"] = "تتبع قوس قزح",
        ["de"] = "Regenbogen-Tracers",
        ["en"] = "Rainbow Tracers",
        ["es"] = "Trazadores Arcoiris",
        ["fr"] = "Traceurs Arc-en-ciel",
        ["pt"] = "Traçadores Arco-íris",
        ["ru"] = "Радужные трейсеры",
        ["tr"] = "Gökkuşağı İzleyiciler",
    },
    ["Range Color"] = {
        ["ar"] = "لون المدى",
        ["de"] = "Bereichsfarbe",
        ["en"] = "Range Color",
        ["es"] = "Color de Rango",
        ["fr"] = "Couleur de Portée",
        ["pt"] = "Cor do Alcance",
        ["ru"] = "Цвет радиуса",
        ["tr"] = "Mesafe Rengi",
    },
    ["Range Transparency"] = {
        ["ar"] = "شفافية المدى",
        ["de"] = "Bereichstransparenz",
        ["en"] = "Range Transparency",
        ["es"] = "Transparencia de Rango",
        ["fr"] = "Transparence de Portée",
        ["pt"] = "Transparência do Alcance",
        ["ru"] = "Прозрачность радиуса",
        ["tr"] = "Mesafe Şeffaflığı",
    },
    ["Rejoin Server"] = {
        ["ar"] = "إعادة دخول السيرفر",
        ["de"] = "Server neu betreten",
        ["en"] = "Rejoin Server",
        ["es"] = "Volver a Entrar al Servidor",
        ["fr"] = "Rejoindre le Serveur",
        ["pt"] = "Reentrar no Servidor",
        ["ru"] = "Перезайти на сервер",
        ["tr"] = "Sunucuya Yeniden Katıl",
    },
    ["S.T.K.W.C.T.P. Range"] = {
        ["ar"] = "مدى سحب السكين التلقائي",
        ["de"] = "Messer-Wechselbereich",
        ["en"] = "S.T.K.W.C.T.P. Range",
        ["es"] = "Rango de Equipar Cuchillo Auto",
        ["fr"] = "Portée du Couteau Automatique",
        ["pt"] = "Alcance de Equipar Faca Auto",
        ["ru"] = "Дистанция авто-ножа",
        ["tr"] = "Otomatik Bıçak Geçiş Mesafesi",
    },
    ["S.T.K.W.C.T.P. Range Color"] = {
        ["ar"] = "لون مدى سحب السكين",
        ["de"] = "Wechselbereich-Farbe",
        ["en"] = "S.T.K.W.C.T.P. Range Color",
        ["es"] = "Color de Rango de Cuchillo Auto",
        ["fr"] = "Couleur de Portée du Couteau",
        ["pt"] = "Cor do Alcance da Faca",
        ["ru"] = "Цвет дистанции авто-ножа",
        ["tr"] = "Bıçak Geçiş Alanı Rengi",
    },
    ["S.T.K.W.C.T.P. Range Transparency"] = {
        ["ar"] = "شفافية مدى سحب السكين",
        ["de"] = "Wechselbereich-Transparenz",
        ["en"] = "S.T.K.W.C.T.P. Range Transparency",
        ["es"] = "Transparencia de Rango de Cuchillo",
        ["fr"] = "Transparence de Portée du Couteau",
        ["pt"] = "Transparência do Alcance",
        ["ru"] = "Прозрачность дистанции авто-ножа",
        ["tr"] = "Bıçak Geçiş Alanı Şeffaflığı",
    },
    ["SP Hub"] = {
        ["ar"] = "SP Hub",
        ["de"] = "SP Hub",
        ["en"] = "SP Hub",
        ["es"] = "SP Hub",
        ["fr"] = "SP Hub",
        ["pt"] = "SP Hub",
        ["ru"] = "SP Hub",
        ["tr"] = "SP Hub",
    },
    ["SP Hub Channels"] = {
        ["ar"] = "قنوات SP Hub",
        ["de"] = "SP Hub Kanäle",
        ["en"] = "SP Hub Channels",
        ["es"] = "Canales de SP Hub",
        ["fr"] = "Chaînes SP Hub",
        ["pt"] = "Canais do SP Hub",
        ["ru"] = "Каналы SP Hub",
        ["tr"] = "SP Hub Kanalları",
    },
    ["SP Hub | Flick | 1.0v"] = {
        ["ar"] = "SP Hub | Flick | 1.0v",
        ["de"] = "SP Hub | Flick | 1.0v",
        ["en"] = "SP Hub | Flick | 1.0v",
        ["es"] = "SP Hub | Flick | 1.0v",
        ["fr"] = "SP Hub | Flick | 1.0v",
        ["pt"] = "SP Hub | Flick | 1.0v",
        ["ru"] = "SP Hub | Flick | 1.0v",
        ["tr"] = "SP Hub | Flick | 1.0v",
    },
    ["Server"] = {
        ["ar"] = "السيرفر",
        ["de"] = "Server",
        ["en"] = "Server",
        ["es"] = "Servidor",
        ["fr"] = "Serveur",
        ["pt"] = "Servidor",
        ["ru"] = "Сервер",
        ["tr"] = "Sunucu",
    },
    ["Set Language"] = {
        ["ar"] = "تغيير اللغة",
        ["de"] = "Sprache einstellen",
        ["en"] = "Set Language",
        ["es"] = "Cambiar Idioma",
        ["fr"] = "Changer la Langue",
        ["pt"] = "Mudar Idioma",
        ["ru"] = "Сменить язык",
        ["tr"] = "Dili Ayarla",
    },
    ["Show Bullet Trail"] = {
        ["ar"] = "إظهار مسارات الرصاص",
        ["de"] = "Kugelspuren anzeigen",
        ["en"] = "Show Bullet Trail",
        ["es"] = "Mostrar Estelas de Bala",
        ["fr"] = "Afficher Traînées de Balles",
        ["pt"] = "Mostrar Rastros de Bala",
        ["ru"] = "Показать следы от пуль",
        ["tr"] = "Mermi İzlerini Göster",
    },
    ["Show FOV"] = {
        ["ar"] = "إظهار دائرة الرؤية",
        ["de"] = "FOV anzeigen",
        ["en"] = "Show FOV",
        ["es"] = "Mostrar FOV",
        ["fr"] = "Afficher le FOV",
        ["pt"] = "Mostrar FOV",
        ["ru"] = "Показать FOV",
        ["tr"] = "Görüş Alanını Göster",
    },
    ["Show S.T.K.W.C.T.P. Range"] = {
        ["ar"] = "إظهار مدى سحب السكين",
        ["de"] = "Wechselbereich anzeigen",
        ["en"] = "Show S.T.K.W.C.T.P. Range",
        ["es"] = "Mostrar Rango de Cuchillo Auto",
        ["fr"] = "Afficher la Portée du Couteau",
        ["pt"] = "Mostrar Alcance da Faca",
        ["ru"] = "Показать дистанцию авто-ножа",
        ["tr"] = "Bıçak Geçiş Mesafesini Göster",
    },
    ["Show Switch Range"] = {
        ["ar"] = "إظهار مدى التبديل",
        ["de"] = "Wechselbereich anzeigen",
        ["en"] = "Show Switch Range",
        ["es"] = "Mostrar Rango de Cambio",
        ["fr"] = "Afficher la Distance de Changement",
        ["pt"] = "Mostrar Alcance de Troca",
        ["ru"] = "Показать дистанцию переключения",
        ["tr"] = "Geçiş Mesafesini Göster",
    },
    ["Status"] = {
        ["ar"] = "الحالة",
        ["de"] = "Status",
        ["en"] = "Status",
        ["es"] = "Estado",
        ["fr"] = "Statut",
        ["pt"] = "Status",
        ["ru"] = "Статус",
        ["tr"] = "Durum",
    },
    ["Switch Range"] = {
        ["ar"] = "مدى التبديل",
        ["de"] = "Wechselbereich",
        ["en"] = "Switch Range",
        ["es"] = "Rango de Cambio",
        ["fr"] = "Distance de Changement",
        ["pt"] = "Alcance de Troca",
        ["ru"] = "Дистанция переключения",
        ["tr"] = "Geçiş Mesafesi",
    },
    ["Switch To Knife When Close To Player"] = {
        ["ar"] = "تبديل للسكين عند الاقتراب",
        ["de"] = "Bei Spielernähe auf Messer wechseln",
        ["en"] = "Switch To Knife When Close To Player",
        ["es"] = "Equipar Cuchillo al Acercarse",
        ["fr"] = "Sortir le Couteau si Proche",
        ["pt"] = "Equipar Faca ao Aproximar",
        ["ru"] = "Свап на нож при сближении",
        ["tr"] = "Oyuncuya Yaklaşınca Bıçağa Geç",
    },
    ["Telegram Channel"] = {
        ["ar"] = "قناة تيليجرام",
        ["de"] = "Telegram Kanal",
        ["en"] = "Telegram Channel",
        ["es"] = "Canal de Telegram",
        ["fr"] = "Chaîne Telegram",
        ["pt"] = "Canal do Telegram",
        ["ru"] = "Телеграм Канал",
        ["tr"] = "Telegram Kanalı",
    },
    ["The link has been copied successfully."] = {
        ["ar"] = "تم نسخ الرابط بنجاح.",
        ["de"] = "Der Link wurde erfolgreich kopiert.",
        ["en"] = "The link has been copied successfully.",
        ["es"] = "El enlace se ha copiado con éxito.",
        ["fr"] = "Le lien a été copié avec succès.",
        ["pt"] = "O link foi copiado com sucesso.",
        ["ru"] = "Ссылка успешно скопирована.",
        ["tr"] = "Bağlantı başarıyla kopyalandı.",
    },
    ["This will take some sec for loading"] = {
        ["ar"] = "سيستغرق هذا بعض الثواني للتحميل",
        ["de"] = "Das Laden dauert einige Sekunden",
        ["en"] = "This will take some sec for loading",
        ["es"] = "Esto tardará unos segundos en cargarse",
        ["fr"] = "Cela prendra quelques secondes pour le chargement",
        ["pt"] = "Isso levará alguns segundos para carregar",
        ["ru"] = "Это займет несколько секунд для загрузки",
        ["tr"] = "Yüklenmesi birkaç saniye sürecek",
    },
    ["Tracer Color"] = {
        ["ar"] = "لون التتبع",
        ["de"] = "Tracer-Farbe",
        ["en"] = "Tracer Color",
        ["es"] = "Color de Trazador",
        ["fr"] = "Couleur du Traceur",
        ["pt"] = "Cor do Traçador",
        ["ru"] = "Цвет трейсеров",
        ["tr"] = "İzleyici Rengi",
    },
    ["Tracer Position"] = {
        ["ar"] = "موقع التتبع",
        ["de"] = "Tracer-Position",
        ["en"] = "Tracer Position",
        ["es"] = "Posición de Trazador",
        ["fr"] = "Position du Traceur",
        ["pt"] = "Posição do Traçador",
        ["ru"] = "Позиция трейсеров",
        ["tr"] = "İzleyici Konumu",
    },
    ["Tracers"] = {
        ["ar"] = "خطوط التتبع",
        ["de"] = "Tracers",
        ["en"] = "Tracers",
        ["es"] = "Trazadores",
        ["fr"] = "Traceurs",
        ["pt"] = "Traçadores",
        ["ru"] = "Трейсеры",
        ["tr"] = "İzleyiciler",
    },
    ["WalkSpeed"] = {
        ["ar"] = "سرعة المشي",
        ["de"] = "Laufgeschwindigkeit",
        ["en"] = "WalkSpeed",
        ["es"] = "Velocidad de Caminado",
        ["fr"] = "Vitesse de Marche",
        ["pt"] = "Velocidade de Caminhada",
        ["ru"] = "Скорость ходьбы",
        ["tr"] = "Yürüme Hızı",
    },
    ["X-Ray"] = {
        ["ar"] = "رؤية من خلال الجدران (X-Ray)",
        ["de"] = "Röntgenblick",
        ["en"] = "X-Ray",
        ["es"] = "Rayos X",
        ["fr"] = "X-Ray",
        ["pt"] = "Raio-X",
        ["ru"] = "Рентген",
        ["tr"] = "Röntgen",
    },
    ["X-Ray Transparency"] = {
        ["ar"] = "شفافية الـ X-Ray",
        ["de"] = "Röntgen-Transparenz",
        ["en"] = "X-Ray Transparency",
        ["es"] = "Transparencia de Rayos X",
        ["fr"] = "Transparence X-Ray",
        ["pt"] = "Transparência do Raio-X",
        ["ru"] = "Прозрачность рентгена",
        ["tr"] = "Röntgen Şeffaflığı",
    },
    ["YouTube Channel"] = {
        ["ar"] = "قناة يوتيوب",
        ["de"] = "YouTube Kanal",
        ["en"] = "YouTube Channel",
        ["es"] = "Canal de YouTube",
        ["fr"] = "Chaîne YouTube",
        ["pt"] = "Canal do YouTube",
        ["ru"] = "Ютуб Канал",
        ["tr"] = "YouTube Kanalı",
    },
    ["by SP Hub"] = {
        ["ar"] = "بواسطة SP Hub",
        ["de"] = "von SP Hub",
        ["en"] = "by SP Hub",
        ["es"] = "por SP Hub",
        ["fr"] = "par SP Hub",
        ["pt"] = "por SP Hub",
        ["ru"] = "от SP Hub",
        ["tr"] = "SP Hub tarafından",
    }
}
