return {
    ["Info"] = {
        ["en"] = "Info",
        ["ar"] = "المعلومات",
        ["ru"] = "Информация",
        ["pt"] = "Informações",
        ["es"] = "Información",
    },
    ["Language"] = {
        ["en"] = "Language",
        ["ar"] = "اللغة",
        ["ru"] = "Язык",
        ["pt"] = "Idioma",
        ["es"] = "Idioma",
    },
    ["Main"] = {
        ["en"] = "Main",
        ["ar"] = "الرئيسية",
        ["ru"] = "Главная",
        ["pt"] = "Principal",
        ["es"] = "Principal",
    },
    ["Player"] = {
        ["en"] = "Player",
        ["ar"] = "اللاعب",
        ["ru"] = "Игрок",
        ["pt"] = "Jogador",
        ["es"] = "Jugador",
    },
    ["Kill"] = {
        ["en"] = "Kill",
        ["ar"] = "القتال والقتل",
        ["ru"] = "Убийство",
        ["pt"] = "Matar",
        ["es"] = "Matar",
    },
    ["ESP Toggles"] = {
        ["en"] = "ESP Toggles",
        ["ar"] = "تفعيل كاشف الأماكن (ESP)",
        ["ru"] = "Включить ESP",
        ["pt"] = "Ativar ESP",
        ["es"] = "Activar ESP",
    },
    ["ESP Peoples"] = {
        ["en"] = "ESP Peoples",
        ["ar"] = "كشف أدوار اللاعبين (ESP Peoples)",
        ["ru"] = "Игроки ESP",
        ["pt"] = "Jogadores ESP",
        ["es"] = "Jogadores ESP",
    },
    ["ESP Dropped Gun"] = {
        ["en"] = "ESP Dropped Gun",
        ["ar"] = "كشف السلاح الساقط (ESP Dropped Gun)",
        ["ru"] = "ESP на выпавшее оружие",
        ["pt"] = "ESP de arma caída",
        ["es"] = "ESP de arma caída",
    },
    ["Tracers ESP"] = {
        ["en"] = "Tracers ESP",
        ["ar"] = "كاشف خطوط الأماكن (Tracers)",
        ["ru"] = "Трейсеры ESP",
        ["pt"] = "Tracer ESP",
        ["es"] = "Tracer ESP",
    },
    ["Sheriff"] = {
        ["en"] = "Sheriff",
        ["ar"] = "الشرطي (Sheriff)",
        ["ru"] = "Шериф",
        ["pt"] = "Xerife",
        ["es"] = "Sheriff",
    },
    ["Aimbot on Murderer"] = {
        ["en"] = "Aimbot on Murderer",
        ["ar"] = "تصويب تلقائي على القاتل (Aimbot)",
        ["ru"] = "Аимбот на убийцу",
        ["pt"] = "Aimbot no assassino",
        ["es"] = "Aimbot en el asesino",
    },
    ["Auto Grab Gun"] = {
        ["en"] = "Auto Grab Gun",
        ["ar"] = "التقاط السلاح الساقط تلقائياً",
        ["ru"] = "Автоматический подбор оружия",
        ["pt"] = "Pegar arma automaticamente",
        ["es"] = "Recoger arma automáticamente",
    },
    ["Kill The Murder"] = {
        ["en"] = "Kill The Murder",
        ["ar"] = "إطلاق النار على القاتل (Kill The Murder)",
        ["ru"] = "Убить убийцу",
        ["pt"] = "Matar o assassino",
        ["es"] = "Matar al asesino",
    },
    ["Auto Kill All"] = {
        ["en"] = "Auto Kill All",
        ["ar"] = "قتل الجميع تلقائياً (Auto Kill All)",
        ["ru"] = "Убить всех",
        ["pt"] = "Matar Todos",
        ["es"] = "Matar a Todos",
    },
    ["Kill All"] = {
        ["en"] = "Kill All",
        ["ar"] = "قتل الجميع (Kill All)",
        ["ru"] = "Убить всех",
        ["pt"] = "Matar Todos",
        ["es"] = "Matar a Todos",
    },
    ["Auto Kill Murder Mode"] = {
        ["en"] = "Auto Kill Murder Mode",
        ["ar"] = "وضعية قتل القاتل (Auto Kill Murder Mode)",
        ["ru"] = "Режим авто-убийства убийцы",
        ["pt"] = "Modo Auto Matar Assassino",
        ["es"] = "Modo Auto Matar Asesino",
    },
    ["Shoot Visible"] = {
        ["en"] = "Shoot Visible",
        ["ar"] = "الضرب عند الظهور (Shoot Visible)",
        ["ru"] = "Стрелять при видимости",
        ["pt"] = "Atirar ao ver",
        ["es"] = "Disparar al ver",
    },
    ["Teleport & Shoot"] = {
        ["en"] = "Teleport & Shoot",
        ["ar"] = "الانتقال والضرب (Teleport & Shoot)",
        ["ru"] = "Телепорт и выстрел",
        ["pt"] = "Teleporte e Atire",
        ["es"] = "Teletransportar y Disparar",
    },
    ["Auto Kill All Mode"] = {
        ["en"] = "Auto Kill All Mode",
        ["ar"] = "وضعية قتل الجميع (Auto Kill All Mode)",
        ["ru"] = "Режим авто-убийства всех",
        ["pt"] = "Modo Auto Matar Todos",
        ["es"] = "Modo Auto Matar Todos",
    },
    ["Teleport to Everyone"] = {
        ["en"] = "Teleport to Everyone",
        ["ar"] = "الانتقال للكل (Teleport to Everyone)",
        ["ru"] = "Телепорт ко всем",
        ["pt"] = "Teleporte para Todos",
        ["es"] = "Teletransportar a Todos",
    },
    ["Bring Everyone"] = {
        ["en"] = "Bring Everyone",
        ["ar"] = "سحب الكل (Bring Everyone)",
        ["ru"] = "Стянуть всех",
        ["pt"] = "Puxar Todos",
        ["es"] = "Traer a Todos",
    },
    ["Auto Evade Murderer"] = {
        ["en"] = "Auto Evade Murderer",
        ["ar"] = "هروب تلقائي ذكي من القاتل",
        ["ru"] = "Автоматический побег от убийцы",
        ["pt"] = "Auto evasão de assassino",
        ["es"] = "Auto evasión de asesino",
    },
    ["Evaded from the Murderer!"] = {
        ["en"] = "Evaded from the Murderer!",
        ["ar"] = "تم الهروب من القاتل بنجاح!",
        ["ru"] = "Успешно сбежал от убийцы!",
        ["pt"] = "Evasão de assassino com sucesso!",
        ["es"] = "¡Evasión de asesino con éxito!",
    },
    ["Protection"] = {
        ["en"] = "Protection",
        ["ar"] = "الحماية والأمان",
        ["ru"] = "Защита",
        ["pt"] = "Proteção",
        ["es"] = "Protección",
    },
    ["Protection From Exploiters"] = {
        ["en"] = "Protection From Exploiters",
        ["ar"] = "حماية من الهاكرز (Exploiters)",
        ["ru"] = "Защита от читеров",
        ["pt"] = "Proteção contra exploiters",
        ["es"] = "Protección contra exploiters",
    },
    ["Anti Fling"] = {
        ["en"] = "Anti Fling",
        ["ar"] = "مقاومة الإلقاء (Anti Fling)",
        ["ru"] = "Анти-Флинг",
        ["pt"] = "Anti Fling",
        ["es"] = "Anti Fling",
    },
    ["FE Invisibility"] = {
        ["en"] = "FE Invisibility",
        ["ar"] = "ميزة الاختفاء (FE Invisibility)",
        ["ru"] = "Невидимость (FE)",
        ["pt"] = "Invisibilidade (FE)",
        ["es"] = "Invisibilidad (FE)",
    },
    ["Coin Tween Speed"] = {
        ["en"] = "Coin Tween Speed",
        ["ar"] = "سرعة انتقال تجميع الكوينز",
        ["ru"] = "Скорость сбора монет",
        ["pt"] = "Velocidade de coleta",
        ["es"] = "Velocidad de recolección",
    },
    ["Murderer"] = {
        ["en"] = "Murderer",
        ["ar"] = "القاتل (Murderer)",
        ["ru"] = "Убийца",
        ["pt"] = "Assassino",
        ["es"] = "Asesino",
    },
    ["Kill Aura"] = {
        ["en"] = "Kill Aura",
        ["ar"] = "هالة القتل التلقائي (Kill Aura)",
        ["ru"] = "Килل Аура",
        ["pt"] = "Aura de morte",
        ["es"] = "Aura de muerte",
    },
    ["Auto Kill (Murderer)"] = {
        ["en"] = "Auto Kill (Murderer)",
        ["ar"] = "قتل تلقائي للجميع (للماردر)",
        ["ru"] = "Автоубийство всех (Убийца)",
        ["pt"] = "Matar todos automaticamente (Assassino)",
        ["es"] = "Matar a todos automáticamente (Asesino)",
    },
    ["Autofarm"] = {
        ["en"] = "Autofarm",
        ["ar"] = "تجميع تلقائي (Autofarm)",
        ["ru"] = "Автофарм",
        ["pt"] = "Farm automático",
        ["es"] = "Farm automático",
    },
    ["Auto Collect Coins"] = {
        ["en"] = "Auto Collect Coins",
        ["ar"] = "تجميع الكوينز تلقائياً (Coins)",
        ["ru"] = "Автосбор монет",
        ["pt"] = "Coletar moedas automaticamente",
        ["es"] = "Recolectar monedas automáticamente",
    },
    ["Teleports"] = {
        ["en"] = "Teleports",
        ["ar"] = "الانتقالات فوري",
        ["ru"] = "Телепорты",
        ["pt"] = "Teletransportes",
        ["es"] = "Teletransportes",
    },
    ["Teleport to Lobby"] = {
        ["en"] = "Teleport to Lobby",
        ["ar"] = "انتقال إلى اللوبي (Lobby)",
        ["ru"] = "Телепорт в лобби",
        ["pt"] = "Teletransportar para o lobby",
        ["es"] = "Teletransportarse al lobby",
    },
    ["Teleport to Safe Zone"] = {
        ["en"] = "Teleport to Safe Zone",
        ["ar"] = "انتقال إلى منطقة آمنة",
        ["ru"] = "Телепорт в безопасную зону",
        ["pt"] = "Teletransportar para zona segura",
        ["es"] = "Teletransportarse a zona segura",
    },
    ["Noclip"] = {
        ["en"] = "Noclip",
        ["ar"] = "اختراق الجدران (Noclip)",
        ["ru"] = "Проход сквозь стены",
        ["pt"] = "Atravessar paredes",
        ["es"] = "Atravessar paredes",
    },
    ["WalkSpeed"] = {
        ["en"] = "WalkSpeed",
        ["ar"] = "سرعة المشي",
        ["ru"] = "Скорость ходьбы",
        ["pt"] = "Velocidade de caminhada",
        ["es"] = "Velocidad de caminata",
    },
    ["JumpPower"] = {
        ["en"] = "JumpPower",
        ["ar"] = "قوة القفز",
        ["ru"] = "Сила прыжка",
        ["pt"] = "Poder de pulo",
        ["es"] = "Poder de salto",
    },
    ["Settings ⚙️"] = {
        ["en"] = "Settings ⚙️",
        ["ar"] = "الإعدادات ⚙️",
        ["ru"] = "Настройки ⚙️",
        ["pt"] = "Configurações ⚙️",
        ["es"] = "Ajustes ⚙️",
    },
    ["Setting"] = {
        ["en"] = "Setting",
        ["ar"] = "الإعدادات",
        ["ru"] = "Настройки",
        ["pt"] = "Configuração",
        ["es"] = "Configuración",
    },
    ["Mod"] = {
        ["en"] = "Mod",
        ["ar"] = "تعديلات (Mod)",
        ["ru"] = "Моды",
        ["pt"] = "Modificações",
        ["es"] = "Modificaciones",
    },
    ["Free Cam"] = {
        ["en"] = "Free Cam",
        ["ar"] = "كاميرا حرة (Free Cam)",
        ["ru"] = "Свободная камера",
        ["pt"] = "Câmera livre",
        ["es"] = "Cámara libre",
    },
    ["Free Cam Speed (Mobile)"] = {
        ["en"] = "Free Cam Speed (Mobile)",
        ["ar"] = "سرعة الكاميرا الحرة (موبايل)",
        ["ru"] = "Скорость свободной камеры (моб)",
        ["pt"] = "Velocidade da câmera livre (Móvel)",
        ["es"] = "Velocidad de cámara livre (Móvil)",
    },
    ["Performance"] = {
        ["en"] = "Performance",
        ["ar"] = "الأداء (Performance)",
        ["ru"] = "Производительность",
        ["pt"] = "Desempenho",
        ["es"] = "Rendimiento",
    },
    ["FPS Booster (Delete Textures)"] = {
        ["en"] = "FPS Booster (Delete Textures)",
        ["ar"] = "معزز الإطارات (حذف الملمس)",
        ["ru"] = "Бустер FPS (удалить текстуры)",
        ["pt"] = "Aumento de FPS (Deletar texturas)",
        ["es"] = "Potenciador de FPS (Eliminar texturas)",
    },
    ["Disable Shadows & Fog"] = {
        ["en"] = "Disable Shadows & Fog",
        ["ar"] = "إغلاق الظلال والضباب",
        ["ru"] = "Отключить тени и туман",
        ["pt"] = "Desativar sombras e neblina",
        ["es"] = "Desactivar sombras y niebla",
    },
    ["Smooth Plastic World"] = {
        ["en"] = "Smooth Plastic World",
        ["ar"] = "عالم بلاستيك ناعم",
        ["ru"] = "Гладкий пластиковый мир",
        ["pt"] = "Mundo de plástico liso",
        ["es"] = "Mundo de plástico liso",
    },
    ["Textures deleted! FPS Boosted."] = {
        ["en"] = "Textures deleted! FPS Boosted.",
        ["ar"] = "تم حذف الملمس! اللعبة أسرع الآن.",
        ["ru"] = "Текстуры удалены! FPS повышен.",
        ["pt"] = "Texturas deletadas! FPS aumentado.",
        ["es"] = "¡Texturas eliminadas! FPS aumentado.",
    },
    ["Shadows disabled!"] = {
        ["en"] = "Shadows disabled!",
        ["ar"] = "تم إغلاق الظلال!",
        ["ru"] = "Тени отключены!",
        ["pt"] = "Sombras desativadas!",
        ["es"] = "¡Sombras desactivadas!",
    },
    ["World set to Smooth Plastic!"] = {
        ["en"] = "World set to Smooth Plastic!",
        ["ar"] = "تم تحويل العالم لبلاستيك ناعم!",
        ["ru"] = "Мир стал гладким пластиком!",
        ["pt"] = "Mundo definido para plástico liso!",
        ["es"] = "¡Mundo configurado a plástico liso!",
    },
    ["World materials restored!"] = {
        ["en"] = "World materials restored!",
        ["ar"] = "تمت استعادة خامات العالم!",
        ["ru"] = "Материалы мира восстановлены!",
        ["pt"] = "Materiais do mundo restaurados!",
        ["es"] = "¡Materiales del mundo restaurados!",
    },
    ["Welcome to SP Hub! Enjoy your first session ad-free!"] = {
        ["en"] = "Welcome to SP Hub! Enjoy your first session ad-free!",
        ["ar"] = "مرحباً بك في SP Hub! استمتع بجلستك الأولى بدون إعلانات!",
        ["ru"] = "Добро пожаловать в SP Hub! Играйте без рекламы при первом запуске!",
        ["pt"] = "Bem-vindo ao SP Hub! Aproveite sua primeira sessão sem anúncios!",
        ["es"] = "¡Bienvenido a SP Hub! ¡Disfruta de tu primera sessão sin anuncios!",
    },
    ["🔑 Key System"] = {
        ["en"] = "🔑 Key System",
        ["ar"] = "🔑 نظام المفتاح",
        ["ru"] = "🔑 Ключевая система",
        ["pt"] = "🔑 Sistema de chave",
        ["es"] = "🔑 Sistema de clave",
    },
    ["This script is Keyless! However, some exclusive premium features require a key to unlock."] = {
        ["en"] = "This script is Keyless! However, some exclusive premium features require a key to unlock.",
        ["ar"] = "هذا السكريبت يعمل بدون مفتاح (Keyless)! لكن هنالك ميزات بريميوم حصرية تتطلب مفتاحاً لاستخدامها.",
        ["ru"] = "Этот скрипт работает без ключа! Но для некоторых премиум-функций требуется ключ.",
        ["pt"] = "Este script não precisa de chave! No entanto, alguns recursos premium exclusivos requerem uma chave para desbloquear.",
        ["es"] = "¡Este script no requiere clave! Sin embargo, algunas funciones premium exclusivas requieren una clave para desbloquear.",
    },
    ["Copied"] = {
        ["en"] = "Copied",
        ["ar"] = "تم النسخ",
        ["ru"] = "Скопировано",
        ["pt"] = "Copiado",
        ["es"] = "Copiado",
    },
    ["Website URL copied to clipboard"] = {
        ["en"] = "Website URL copied to clipboard",
        ["ar"] = "تم نسخ رابط الموقع للحافظة",
        ["ru"] = "Ссылка на сайт скопирована в буфер обмена",
        ["pt"] = "URL do site copiada para a área de transferência",
        ["es"] = "URL del sitio web copiada al portapapeles",
    },
    ["Your coin bag is full! Autofarm paused."] = {
        ["en"] = "Your coin bag is full! Autofarm paused.",
        ["ar"] = "حقيبة العملات ممتلئة! تم إيقاف التجميع تلقائياً.",
        ["ru"] = "Ваш мешок для монет полон! Автофарм приостановлен.",
        ["pt"] = "Sua bolsa de moedas está cheia! Farm automático pausado.",
        ["es"] = "¡Tu bolsa de monedas está llena! Auto-farm pausado.",
    },
    ["Anti Void"] = {
        ["en"] = "Anti Void",
        ["ar"] = "الحماية من السقوط (Anti Void)",
        ["ru"] = "Анти-Бездна",
        ["pt"] = "Anti Void",
        ["es"] = "Anti Void",
    },
    ["Saved from falling into the void!"] = {
        ["en"] = "Saved from falling into the void!",
        ["ar"] = "تم إنقاذك من السقوط في الهاوية!",
        ["ru"] = "Спасен от падения в бездну!",
        ["pt"] = "Salvo de cair no vazio!",
        ["es"] = "¡Salvado de caer al vacío!",
    },
    ["Server Utility"] = {
        ["en"] = "Server Utility",
        ["ar"] = "خيارات السيرفر",
        ["ru"] = "Утилиты сервера",
        ["pt"] = "Utilitários de servidor",
        ["es"] = "Utilitarios de servidor",
    },
    ["Rejoin Server"] = {
        ["en"] = "Rejoin Server",
        ["ar"] = "إعادة دخول السيرفر (Rejoin)",
        ["ru"] = "Перезайти на сервер",
        ["pt"] = "Reentrar no servidor",
        ["es"] = "Reingresar al servidor",
    },
    ["Server Hop"] = {
        ["en"] = "Server Hop",
        ["ar"] = "الانتقال لسيرفر آخر (Server Hop)",
        ["ru"] = "Сменить сервер",
        ["pt"] = "Trocar de servidor",
        ["es"] = "Cambiar de servidor",
    },
    ["Instant Grab Gun"] = {
        ["en"] = "Instant Grab Gun",
        ["ar"] = "التقاط لحظي للمسدس (Grab Gun)",
        ["ru"] = "Быстрый подбор оружия",
        ["pt"] = "Pegar arma instantâneo",
        ["es"] = "Recoger arma instantáneo",
    },
    ["Dropped Gun"] = {
        ["en"] = "Dropped Gun",
        ["ar"] = "سلاح ساقط",
        ["ru"] = "Выпавшее оружие",
        ["pt"] = "Arma caída",
        ["es"] = "Arma caída",
    },
    ["A gun has dropped on the map!"] = {
        ["en"] = "A gun has dropped on the map!",
        ["ar"] = "لقد سقط سلاح على الخريطة!",
        ["ru"] = "Оружие выпало на карте!",
        ["pt"] = "Uma arma caiu no mapa!",
        ["es"] = "¡Una arma ha caído en el mapa!",
    },
    ["A gun has dropped! Do you want to teleport and grab it?"] = {
        ["en"] = "A gun has dropped! Do you want to teleport and grab it?",
        ["ar"] = "سقط مسدس! هل تريد الانتقال والتقاطه؟",
        ["ru"] = "Оружие выпало! Хотите телепортироваться и подобрать его?",
        ["pt"] = "Uma arma caiu! Quer se teletransportar e pegá-la?",
        ["es"] = "¿Una arma ha caído! ¿Quieres teletransportarte y recogerla?",
    },
    ["Yes"] = {
        ["en"] = "Yes",
        ["ar"] = "نعم",
        ["ru"] = "Да",
        ["pt"] = "Sim",
        ["es"] = "Sí",
    },
    ["No"] = {
        ["en"] = "No",
        ["ar"] = "لا",
        ["ru"] = "Нет",
        ["pt"] = "Não",
        ["es"] = "Não",
    },
    ["Show HitBox"] = {
        ["en"] = "Show HitBox",
        ["ar"] = "عرض الهيت بوكس (Show HitBox)",
        ["ru"] = "Показать хитбокс",
        ["pt"] = "Mostrar Hitbox",
        ["es"] = "Mostrar Hitbox",
    },
    ["Rainbow Gun"] = {
        ["en"] = "Rainbow Gun",
        ["ar"] = "سلاح قوس قزح (Rainbow Gun)",
        ["ru"] = "Радужный пистолет",
        ["pt"] = "Arma Arco-Íris",
        ["es"] = "Arma Arcoíris",
    },
    ["Auto Fling All"] = {
        ["en"] = "Auto Fling All",
        ["ar"] = "طرد الجميع طائراً (Auto Fling All)",
        ["ru"] = "Авто-флинг всех",
        ["pt"] = "Auto Fling Todos",
        ["es"] = "Auto Fling Todos",
    },
    ["Murderer ESP"] = {
        ["en"] = "Murderer ESP",
        ["ar"] = "كشف القاتل فقط (Murderer ESP)",
        ["ru"] = "ESP на убийцу",
        ["pt"] = "ESP do assassino",
        ["es"] = "ESP del asesino",
    },
    ["Sheriff ESP"] = {
        ["en"] = "Sheriff ESP",
        ["ar"] = "كشف الشرطي فقط (Sheriff ESP)",
        ["ru"] = "ESP на шерифа",
        ["pt"] = "ESP do xerife",
        ["es"] = "ESP del sheriff",
    },
    ["Murderer Tracer"] = {
        ["en"] = "Murderer Tracer",
        ["ar"] = "مؤشر القاتل فقط (Murderer Tracer)",
        ["ru"] = "Трейсер на убийцу",
        ["pt"] = "Tracer do assassino",
        ["es"] = "Tracer del asesino",
    },
    ["Sheriff Tracer"] = {
        ["en"] = "Sheriff Tracer",
        ["ar"] = "مؤشر الشرطي فقط (Sheriff Tracer)",
        ["ru"] = "Трейсер на шерифа",
        ["pt"] = "Tracer do xerife",
        ["es"] = "Tracer del sheriff",
    },
    ["Dropped Gun Alert"] = {
        ["en"] = "Dropped Gun Alert",
        ["ar"] = "تنبيه السلاح الساقط",
        ["ru"] = "Оповещение о выпавшем оружии",
        ["pt"] = "Alerta de arma caída",
        ["es"] = "Alerta de arma caída",
    },
    ["Names ESP"] = {
        ["en"] = "Names ESP",
        ["ar"] = "كشف الأسماء (Names ESP)",
        ["ru"] = "ESP на имена",
        ["pt"] = "ESP de nomes",
        ["es"] = "ESP de nombres",
    },
    ["Fling Target Player"] = {
        ["en"] = "Fling Target Player",
        ["ar"] = "تحديد لاعب للطرد",
        ["ru"] = "Цель для флинга",
        ["pt"] = "Alvo do fling",
        ["es"] = "Objetivo del fling",
    },
    ["Fling Player"] = {
        ["en"] = "Fling Player",
        ["ar"] = "طرد اللاعب المحدد (Fling Player)",
        ["ru"] = "Флинг игрока",
        ["pt"] = "Fling no jogador",
        ["es"] = "Fling al jugador",
    },
    ["Fling Murderer"] = {
        ["en"] = "Fling Murderer",
        ["ar"] = "طرد القاتل (Fling Murderer)",
        ["ru"] = "Флинг убийцы",
        ["pt"] = "Fling no assassino",
        ["es"] = "Fling al asesino",
    },
    ["Fling Sheriff"] = {
        ["en"] = "Fling Sheriff",
        ["ar"] = "طرد الشرطي (Fling Sheriff)",
        ["ru"] = "Флинг шерифа",
        ["pt"] = "Fling no xerife",
        ["es"] = "Fling al sheriff",
    },
    ["Fling Touch"] = {
        ["en"] = "Fling Touch",
        ["ar"] = "لمسة الطرد (Fling Touch)",
        ["ru"] = "Флинг при касании",
        ["pt"] = "Fling por toque",
        ["es"] = "Fling por toque",
    },
    ["Teleport to Active Map"] = {
        ["en"] = "Teleport to Active Map",
        ["ar"] = "انتقال إلى الماب الحالي (Active Map)",
        ["ru"] = "Телепорт на карту",
        ["pt"] = "Teleportar para o mapa",
        ["es"] = "Teletransportarse al mapa",
    },
    ["Teleport Above Map"] = {
        ["en"] = "Teleport Above Map",
        ["ar"] = "انتقال فوق الماب (Above Map)",
        ["ru"] = "Телепорт над картой",
        ["pt"] = "Teleportar acima do mapa",
        ["es"] = "Teletransportarse arriba del mapa",
    },
    ["Select Player"] = {
        ["en"] = "Select Player",
        ["ar"] = "اختر اللاعب",
        ["ru"] = "Выбрать игрока",
        ["pt"] = "Selecionar jogador",
        ["es"] = "Seleccionar jugador",
    },
    ["Teleport to Selected Player"] = {
        ["en"] = "Teleport to Selected Player",
        ["ar"] = "انتقال للاعب المحدد",
        ["ru"] = "Телепорт к игроку",
        ["pt"] = "Teleportar para o jogador",
        ["es"] = "Teletransportarse al jogador",
    },
    ["Player Speed"] = {
        ["en"] = "Player Speed",
        ["ar"] = "تفعيل السرعة (Player Speed)",
        ["ru"] = "Скорость игрока",
        ["pt"] = "Velocidade do jogador",
        ["es"] = "Velocidad del jugador",
    },
    ["Player Jump Power"] = {
        ["en"] = "Player Jump Power",
        ["ar"] = "تفعيل القفز (Player Jump Power)",
        ["ru"] = "Прыжок игрока",
        ["pt"] = "Força do pulo",
        ["es"] = "Fuerza del salto",
    },
    ["Helpers"] = {
        ["en"] = "Helpers",
        ["ar"] = "المساعدين (Helpers)",
        ["ru"] = "Помощники",
        ["pt"] = "Ajudantes",
        ["es"] = "Ayudantes",
    },
    ["Faster Kill Murder Button"] = {
        ["en"] = "Faster Kill Murder Button",
        ["ar"] = "زر القتل السريع للماردر (Faster Kill)",
        ["ru"] = "Кнопка быстрого убийства убийцы",
        ["pt"] = "Botão de matar assassino rápido",
        ["es"] = "Botón de matar asesino rápido",
    },
}
