return {
    ["Info"] = {
        ["en"] = "Info",
        ["ar"] = "المعلومات",
        ["ru"] = "Информация",
        ["tr"] = "Info",
        ["es"] = "Información",
        ["fr"] = "Info",
        ["de"] = "Info",
        ["pt"] = "Informações",
    },
    ["Language"] = {
        ["en"] = "Language",
        ["ar"] = "اللغة",
        ["ru"] = "Язык",
        ["tr"] = "Language",
        ["es"] = "Idioma",
        ["fr"] = "Language",
        ["de"] = "Language",
        ["pt"] = "Idioma",
    },
    ["Main"] = {
        ["en"] = "Main",
        ["ar"] = "الرئيسية",
        ["ru"] = "Главная",
        ["tr"] = "Main",
        ["es"] = "Principal",
        ["fr"] = "Main",
        ["de"] = "Main",
        ["pt"] = "Principal",
    },
    ["Player"] = {
        ["en"] = "Player",
        ["ar"] = "اللاعب",
        ["ru"] = "Игрок",
        ["tr"] = "Player",
        ["es"] = "Jugador",
        ["fr"] = "Player",
        ["de"] = "Player",
        ["pt"] = "Jogador",
    },
    ["Kill"] = {
        ["en"] = "Kill",
        ["ar"] = "القتال والقتل",
        ["ru"] = "Убийство",
        ["tr"] = "Kill",
        ["es"] = "Matar",
        ["fr"] = "Kill",
        ["de"] = "Kill",
        ["pt"] = "Matar",
    },
    ["ESP Toggles"] = {
        ["en"] = "ESP Toggles",
        ["ar"] = "تفعيل كاشف الأماكن",
        ["ru"] = "Включить ESP",
        ["tr"] = "ESP Toggles",
        ["es"] = "Activar ESP",
        ["fr"] = "ESP Toggles",
        ["de"] = "ESP Toggles",
        ["pt"] = "Ativar ESP",
    },
    ["ESP Players"] = {
        ["en"] = "ESP Players",
        ["ar"] = "كشف اللاعبين (ESP)",
        ["ru"] = "Игроки ESP",
        ["tr"] = "ESP Players",
        ["es"] = "Jogadores ESP",
        ["fr"] = "ESP Players",
        ["de"] = "ESP Players",
        ["pt"] = "Jogadores ESP",
    },
    ["ESP Dropped Gun"] = {
        ["en"] = "ESP Dropped Gun",
        ["ar"] = "كشف السلاح الساقط",
        ["ru"] = "ESP на выпавшее оружие",
        ["tr"] = "ESP Dropped Gun",
        ["es"] = "ESP de arma caída",
        ["fr"] = "ESP Dropped Gun",
        ["de"] = "ESP Dropped Gun",
        ["pt"] = "ESP de arma caída",
    },
    ["ESP Tracers"] = {
        ["en"] = "ESP Tracers",
        ["ar"] = "كاشف خطوط الأماكن",
        ["ru"] = "Трейсеры ESP",
        ["tr"] = "ESP Tracers",
        ["es"] = "Tracer ESP",
        ["fr"] = "ESP Tracers",
        ["de"] = "ESP Tracers",
        ["pt"] = "Tracer ESP",
    },
    ["Sheriff"] = {
        ["en"] = "Sheriff",
        ["ar"] = "الشرطي",
        ["ru"] = "Шериф",
        ["tr"] = "Sheriff",
        ["es"] = "Sheriff",
        ["fr"] = "Sheriff",
        ["de"] = "Sheriff",
        ["pt"] = "Xerife",
    },
    ["Aimbot on Murderer"] = {
        ["en"] = "Aimbot on Murderer",
        ["ar"] = "تصويب تلقائي على القاتل",
        ["ru"] = "Аимбот на убийцу",
        ["tr"] = "Aimbot on Murderer",
        ["es"] = "Aimbot en el asesino",
        ["fr"] = "Aimbot on Murderer",
        ["de"] = "Aimbot on Murderer",
        ["pt"] = "Aimbot no assassino",
    },
    ["Auto Grab Gun"] = {
        ["en"] = "Auto Grab Gun",
        ["ar"] = "التقاط السلاح الساقط تلقائياً",
        ["ru"] = "Автоматический подбор оружия",
        ["tr"] = "Auto Grab Gun",
        ["es"] = "Recoger arma automáticamente",
        ["fr"] = "Auto Grab Gun",
        ["de"] = "Auto Grab Gun",
        ["pt"] = "Pegar arma automaticamente",
    },
    ["Kill The Murder"] = {
        ["en"] = "Kill The Murder",
        ["ar"] = "إطلاق النار على القاتل",
        ["ru"] = "Убить убийцу",
        ["tr"] = "Kill The Murder",
        ["es"] = "Matar al asesino",
        ["fr"] = "Kill The Murder",
        ["de"] = "Kill The Murder",
        ["pt"] = "Matar o assassino",
    },
    ["Auto Kill All"] = {
        ["en"] = "Auto Kill All",
        ["ar"] = "قتل الجميع تلقائياً",
        ["ru"] = "Убить всех",
        ["tr"] = "Auto Kill All",
        ["es"] = "Matar a Todos",
        ["fr"] = "Auto Kill All",
        ["de"] = "Auto Kill All",
        ["pt"] = "Matar Todos",
    },
    ["Kill All"] = {
        ["en"] = "Kill All",
        ["ar"] = "قتل الجميع",
        ["ru"] = "Убить всех",
        ["tr"] = "Kill All",
        ["es"] = "Matar a Todos",
        ["fr"] = "Kill All",
        ["de"] = "Kill All",
        ["pt"] = "Matar Todos",
    },
    ["Deactivated"] = {
        ["en"] = "Deactivated",
        ["ar"] = "ملغي التفعيل",
        ["ru"] = "Deactivated",
        ["tr"] = "Deactivated",
        ["es"] = "Deactivated",
        ["fr"] = "Deactivated",
        ["de"] = "Deactivated",
        ["pt"] = "Deactivated",
    },
    ["Teleport to Selected Player"] = {
        ["en"] = "Teleport to Selected Player",
        ["ar"] = "انتقال للاعب المحدد",
        ["ru"] = "Teleport to Selected Player",
        ["tr"] = "Teleport to Selected Player",
        ["es"] = "Teleport to Selected Player",
        ["fr"] = "Teleport to Selected Player",
        ["de"] = "Teleport to Selected Player",
        ["pt"] = "Teleport to Selected Player",
    },
    ["WalkSpeed"] = {
        ["en"] = "WalkSpeed",
        ["ar"] = "السرعة",
        ["ru"] = "WalkSpeed",
        ["tr"] = "WalkSpeed",
        ["es"] = "WalkSpeed",
        ["fr"] = "WalkSpeed",
        ["de"] = "WalkSpeed",
        ["pt"] = "WalkSpeed",
    },
    ["Auto Fling All"] = {
        ["en"] = "Auto Fling All",
        ["ar"] = "تفجير الجميع تلقائياً",
        ["ru"] = "Auto Fling All",
        ["tr"] = "Auto Fling All",
        ["es"] = "Auto Fling All",
        ["fr"] = "Auto Fling All",
        ["de"] = "Auto Fling All",
        ["pt"] = "Auto Fling All",
    },
    ["🔑 Key System"] = {
        ["en"] = "🔑 Key System",
        ["ar"] = "🔑 نظام المفتاح",
        ["ru"] = "🔑 Key System",
        ["tr"] = "🔑 Key System",
        ["es"] = "🔑 Key System",
        ["fr"] = "🔑 Key System",
        ["de"] = "🔑 Key System",
        ["pt"] = "🔑 Key System",
    },
    ["Waiting..."] = {
        ["en"] = "Waiting...",
        ["ar"] = "جاري الانتظار...",
        ["ru"] = "Waiting...",
        ["tr"] = "Waiting...",
        ["es"] = "Waiting...",
        ["fr"] = "Waiting...",
        ["de"] = "Waiting...",
        ["pt"] = "Waiting...",
    },
    ["Sheriff ESP"] = {
        ["en"] = "Sheriff ESP",
        ["ar"] = "كاشف الشرطي",
        ["ru"] = "Sheriff ESP",
        ["tr"] = "Sheriff ESP",
        ["es"] = "Sheriff ESP",
        ["fr"] = "Sheriff ESP",
        ["de"] = "Sheriff ESP",
        ["pt"] = "Sheriff ESP",
    },
    ["Free Cam Speed (Mobile)"] = {
        ["en"] = "Free Cam Speed (Mobile)",
        ["ar"] = "Free Cam Speed",
        ["ru"] = "Free Cam Speed (Mobile)",
        ["tr"] = "Free Cam Speed (Mobile)",
        ["es"] = "Free Cam Speed (Mobile)",
        ["fr"] = "Free Cam Speed (Mobile)",
        ["de"] = "Free Cam Speed (Mobile)",
        ["pt"] = "Free Cam Speed (Mobile)",
    },
    ["Teleported above active map!"] = {
        ["en"] = "Teleported above active map!",
        ["ar"] = "تم الانتقال فوق الخريطة النشطة!",
        ["ru"] = "Teleported above active map!",
        ["tr"] = "Teleported above active map!",
        ["es"] = "Teleported above active map!",
        ["fr"] = "Teleported above active map!",
        ["de"] = "Teleported above active map!",
        ["pt"] = "Teleported above active map!",
    },
    ["This script is Keyless! However, some exclusive premium features require a key to unlock."] = {
        ["en"] = "This script is Keyless! However, some exclusive premium features require a key to unlock.",
        ["ar"] = "هذا السكريبت يعمل بدون مفتاح! لكن هنالك ميزات بريميوم حصرية تتطلب مفتاحاً لاستخدامها.",
        ["ru"] = "This script is Keyless! However, some exclusive premium features require a key to unlock.",
        ["tr"] = "This script is Keyless! However, some exclusive premium features require a key to unlock.",
        ["es"] = "This script is Keyless! However, some exclusive premium features require a key to unlock.",
        ["fr"] = "This script is Keyless! However, some exclusive premium features require a key to unlock.",
        ["de"] = "This script is Keyless! However, some exclusive premium features require a key to unlock.",
        ["pt"] = "This script is Keyless! However, some exclusive premium features require a key to unlock.",
    },
    ["FPS Booster (Delete Textures)"] = {
        ["en"] = "FPS Booster (Delete Textures)",
        ["ar"] = "FPS Booster",
        ["ru"] = "FPS Booster (Delete Textures)",
        ["tr"] = "FPS Booster (Delete Textures)",
        ["es"] = "FPS Booster (Delete Textures)",
        ["fr"] = "FPS Booster (Delete Textures)",
        ["de"] = "FPS Booster (Delete Textures)",
        ["pt"] = "FPS Booster (Delete Textures)",
    },
    ["Key"] = {
        ["en"] = "Key",
        ["ar"] = "المفتاح",
        ["ru"] = "Key",
        ["tr"] = "Key",
        ["es"] = "Key",
        ["fr"] = "Key",
        ["de"] = "Key",
        ["pt"] = "Key",
    },
    ["Checking..."] = {
        ["en"] = "Checking...",
        ["ar"] = "جاري التحقق...",
        ["ru"] = "Checking...",
        ["tr"] = "Checking...",
        ["es"] = "Checking...",
        ["fr"] = "Checking...",
        ["de"] = "Checking...",
        ["pt"] = "Checking...",
    },
    ["Could not find spawn points in active map!"] = {
        ["en"] = "Could not find spawn points in active map!",
        ["ar"] = "لم يتم العثور على نقاط ريسبون في الخريطة النشطة!",
        ["ru"] = "Could not find spawn points in active map!",
        ["tr"] = "Could not find spawn points in active map!",
        ["es"] = "Could not find spawn points in active map!",
        ["fr"] = "Could not find spawn points in active map!",
        ["de"] = "Could not find spawn points in active map!",
        ["pt"] = "Could not find spawn points in active map!",
    },
    ["Success"] = {
        ["en"] = "Success",
        ["ar"] = "نجاح",
        ["ru"] = "Success",
        ["tr"] = "Success",
        ["es"] = "Success",
        ["fr"] = "Success",
        ["de"] = "Success",
        ["pt"] = "Success",
    },
    ["Dropped Gun Alert"] = {
        ["en"] = "Dropped Gun Alert",
        ["ar"] = "تنبيه سقوط السلاح",
        ["ru"] = "Dropped Gun Alert",
        ["tr"] = "Dropped Gun Alert",
        ["es"] = "Dropped Gun Alert",
        ["fr"] = "Dropped Gun Alert",
        ["de"] = "Dropped Gun Alert",
        ["pt"] = "Dropped Gun Alert",
    },
    ["Show HitBox"] = {
        ["en"] = "Show HitBox",
        ["ar"] = "عرض الهيت بوكس",
        ["ru"] = "Show HitBox",
        ["tr"] = "Show HitBox",
        ["es"] = "Show HitBox",
        ["fr"] = "Show HitBox",
        ["de"] = "Show HitBox",
        ["pt"] = "Show HitBox",
    },
    ["Free Cam"] = {
        ["en"] = "Free Cam",
        ["ar"] = "الكاميرا الحرة",
        ["ru"] = "Free Cam",
        ["tr"] = "Free Cam",
        ["es"] = "Free Cam",
        ["fr"] = "Free Cam",
        ["de"] = "Free Cam",
        ["pt"] = "Free Cam",
    },
    ["Troll"] = {
        ["en"] = "Troll",
        ["ar"] = "المقالب والترول",
        ["ru"] = "Troll",
        ["tr"] = "Troll",
        ["es"] = "Troll",
        ["fr"] = "Troll",
        ["de"] = "Troll",
        ["pt"] = "Troll",
    },
    ["Shadows disabled!"] = {
        ["en"] = "Shadows disabled!",
        ["ar"] = "تم إلغاء تفعيل الظلال!",
        ["ru"] = "Shadows disabled!",
        ["tr"] = "Shadows disabled!",
        ["es"] = "Shadows disabled!",
        ["fr"] = "Shadows disabled!",
        ["de"] = "Shadows disabled!",
        ["pt"] = "Shadows disabled!",
    },
    ["Teleport to Lobby"] = {
        ["en"] = "Teleport to Lobby",
        ["ar"] = "انتقال للمكان الرئيسي",
        ["ru"] = "Teleport to Lobby",
        ["tr"] = "Teleport to Lobby",
        ["es"] = "Teleport to Lobby",
        ["fr"] = "Teleport to Lobby",
        ["de"] = "Teleport to Lobby",
        ["pt"] = "Teleport to Lobby",
    },
    ["Murderer Tracer"] = {
        ["en"] = "Murderer Tracer",
        ["ar"] = "خطوط كاشف القاتل",
        ["ru"] = "Murderer Tracer",
        ["tr"] = "Murderer Tracer",
        ["es"] = "Murderer Tracer",
        ["fr"] = "Murderer Tracer",
        ["de"] = "Murderer Tracer",
        ["pt"] = "Murderer Tracer",
    },
    ["Expires"] = {
        ["en"] = "Expires",
        ["ar"] = "تاريخ الانتهاء",
        ["ru"] = "Expires",
        ["tr"] = "Expires",
        ["es"] = "Expires",
        ["fr"] = "Expires",
        ["de"] = "Expires",
        ["pt"] = "Expires",
    },
    ["Murderer ESP"] = {
        ["en"] = "Murderer ESP",
        ["ar"] = "كاشف القاتل",
        ["ru"] = "Murderer ESP",
        ["tr"] = "Murderer ESP",
        ["es"] = "Murderer ESP",
        ["fr"] = "Murderer ESP",
        ["de"] = "Murderer ESP",
        ["pt"] = "Murderer ESP",
    },
    ["Deactivate Key"] = {
        ["en"] = "Deactivate Key",
        ["ar"] = "إلغاء تفعيل المفتاح",
        ["ru"] = "Deactivate Key",
        ["tr"] = "Deactivate Key",
        ["es"] = "Deactivate Key",
        ["fr"] = "Deactivate Key",
        ["de"] = "Deactivate Key",
        ["pt"] = "Deactivate Key",
    },
    ["YouTube Channel"] = {
        ["en"] = "YouTube Channel",
        ["ar"] = "قناة اليوتيوب",
        ["ru"] = "YouTube Channel",
        ["tr"] = "YouTube Channel",
        ["es"] = "YouTube Channel",
        ["fr"] = "YouTube Channel",
        ["de"] = "YouTube Channel",
        ["pt"] = "YouTube Channel",
    },
    ["Names ESP"] = {
        ["en"] = "Names ESP",
        ["ar"] = "كشف الأسماء",
        ["ru"] = "Names ESP",
        ["tr"] = "Names ESP",
        ["es"] = "Names ESP",
        ["fr"] = "Names ESP",
        ["de"] = "Names ESP",
        ["pt"] = "Names ESP",
    },
    ["Status"] = {
        ["en"] = "Status",
        ["ar"] = "الحالة",
        ["ru"] = "Status",
        ["tr"] = "Status",
        ["es"] = "Status",
        ["fr"] = "Status",
        ["de"] = "Status",
        ["pt"] = "Status",
    },
    ["FE Invisibility"] = {
        ["en"] = "FE Invisibility",
        ["ar"] = "الاختفاء الكامل",
        ["ru"] = "FE Invisibility",
        ["tr"] = "FE Invisibility",
        ["es"] = "FE Invisibility",
        ["fr"] = "FE Invisibility",
        ["de"] = "FE Invisibility",
        ["pt"] = "FE Invisibility",
    },
    ["m"] = {
        ["en"] = "m",
        ["ar"] = "دقيقة",
        ["ru"] = "m",
        ["tr"] = "m",
        ["es"] = "m",
        ["fr"] = "m",
        ["de"] = "m",
        ["pt"] = "m",
    },
    ["Saved from falling into the void!"] = {
        ["en"] = "Saved from falling into the void!",
        ["ar"] = "تم إنقاذك من السقوط في الهاوية!",
        ["ru"] = "Saved from falling into the void!",
        ["tr"] = "Saved from falling into the void!",
        ["es"] = "Saved from falling into the void!",
        ["fr"] = "Saved from falling into the void!",
        ["de"] = "Saved from falling into the void!",
        ["pt"] = "Saved from falling into the void!",
    },
    ["Verify Key"] = {
        ["en"] = "Verify Key",
        ["ar"] = "التحقق من المفتاح",
        ["ru"] = "Verify Key",
        ["tr"] = "Verify Key",
        ["es"] = "Verify Key",
        ["fr"] = "Verify Key",
        ["de"] = "Verify Key",
        ["pt"] = "Verify Key",
    },
    ["Expired"] = {
        ["en"] = "Expired",
        ["ar"] = "منتهي الصلاحية",
        ["ru"] = "Expired",
        ["tr"] = "Expired",
        ["es"] = "Expired",
        ["fr"] = "Expired",
        ["de"] = "Expired",
        ["pt"] = "Expired",
    },
    ["Instant Grab Gun"] = {
        ["en"] = "Instant Grab Gun",
        ["ar"] = "التقاط لحظي للمسدس",
        ["ru"] = "Instant Grab Gun",
        ["tr"] = "Instant Grab Gun",
        ["es"] = "Instant Grab Gun",
        ["fr"] = "Instant Grab Gun",
        ["de"] = "Instant Grab Gun",
        ["pt"] = "Instant Grab Gun",
    },
    ["✅ Key Valid"] = {
        ["en"] = "✅ Key Valid",
        ["ar"] = "✅ المفتاح صالح",
        ["ru"] = "✅ Key Valid",
        ["tr"] = "✅ Key Valid",
        ["es"] = "✅ Key Valid",
        ["fr"] = "✅ Key Valid",
        ["de"] = "✅ Key Valid",
        ["pt"] = "✅ Key Valid",
    },
    ["h"] = {
        ["en"] = "h",
        ["ar"] = "ساعة",
        ["ru"] = "h",
        ["tr"] = "h",
        ["es"] = "h",
        ["fr"] = "h",
        ["de"] = "h",
        ["pt"] = "h",
    },
    ["Select Player"] = {
        ["en"] = "Select Player",
        ["ar"] = "اختر لاعب",
        ["ru"] = "Select Player",
        ["tr"] = "Select Player",
        ["es"] = "Select Player",
        ["fr"] = "Select Player",
        ["de"] = "Select Player",
        ["pt"] = "Select Player",
    },
    ["Teleport to Safe Zone"] = {
        ["en"] = "Teleport to Safe Zone",
        ["ar"] = "انتقال للمنطقة الآمنة",
        ["ru"] = "Teleport to Safe Zone",
        ["tr"] = "Teleport to Safe Zone",
        ["es"] = "Teleport to Safe Zone",
        ["fr"] = "Teleport to Safe Zone",
        ["de"] = "Teleport to Safe Zone",
        ["pt"] = "Teleport to Safe Zone",
    },
    ["Successfully pulled and eliminated all players!"] = {
        ["en"] = "Successfully pulled and eliminated all players!",
        ["ar"] = "تم سحب وقتل جميع اللاعبين بنجاح!",
        ["ru"] = "Successfully pulled and eliminated all players!",
        ["tr"] = "Successfully pulled and eliminated all players!",
        ["es"] = "Successfully pulled and eliminated all players!",
        ["fr"] = "Successfully pulled and eliminated all players!",
        ["de"] = "Successfully pulled and eliminated all players!",
        ["pt"] = "Successfully pulled and eliminated all players!",
    },
    ["World set to Smooth Plastic!"] = {
        ["en"] = "World set to Smooth Plastic!",
        ["ar"] = "تم تحويل خامات العالم لبلاستيك ناعم!",
        ["ru"] = "World set to Smooth Plastic!",
        ["tr"] = "World set to Smooth Plastic!",
        ["es"] = "World set to Smooth Plastic!",
        ["fr"] = "World set to Smooth Plastic!",
        ["de"] = "World set to Smooth Plastic!",
        ["pt"] = "World set to Smooth Plastic!",
    },
    ["Enter Key"] = {
        ["en"] = "Enter Key",
        ["ar"] = "أدخل المفتاح",
        ["ru"] = "Enter Key",
        ["tr"] = "Enter Key",
        ["es"] = "Enter Key",
        ["fr"] = "Enter Key",
        ["de"] = "Enter Key",
        ["pt"] = "Enter Key",
    },
    ["Server Utility"] = {
        ["en"] = "Server Utility",
        ["ar"] = "خيارات السيرفر",
        ["ru"] = "Server Utility",
        ["tr"] = "Server Utility",
        ["es"] = "Server Utility",
        ["fr"] = "Server Utility",
        ["de"] = "Server Utility",
        ["pt"] = "Server Utility",
    },
    ["d"] = {
        ["en"] = "d",
        ["ar"] = "يوم",
        ["ru"] = "d",
        ["tr"] = "d",
        ["es"] = "d",
        ["fr"] = "d",
        ["de"] = "d",
        ["pt"] = "d",
    },
    ["Noclip"] = {
        ["en"] = "Noclip",
        ["ar"] = "اختراق الجدران",
        ["ru"] = "Noclip",
        ["tr"] = "Noclip",
        ["es"] = "Noclip",
        ["fr"] = "Noclip",
        ["de"] = "Noclip",
        ["pt"] = "Noclip",
    },
    ["Premium Activated"] = {
        ["en"] = "Premium Activated",
        ["ar"] = "تم تفعيل البريميوم",
        ["ru"] = "Premium Activated",
        ["tr"] = "Premium Activated",
        ["es"] = "Premium Activated",
        ["fr"] = "Premium Activated",
        ["de"] = "Premium Activated",
        ["pt"] = "Premium Activated",
    },
    ["🎁 <font color=\"#ff8c00\">Get 3 Days FREE Premium!</font>"] = {
        ["en"] = "🎁 <font color=\"#ff8c00\">Get 3 Days FREE Premium!</font>",
        ["ar"] = "🎁 <font color=\"#ff8c00\">احصل على 3 أيام بريميوم مجاناً!</font>",
        ["ru"] = "🎁 <font color=\"#ff8c00\">Get 3 Days FREE Premium!</font>",
        ["tr"] = "🎁 <font color=\"#ff8c00\">Get 3 Days FREE Premium!</font>",
        ["es"] = "🎁 <font color=\"#ff8c00\">Get 3 Days FREE Premium!</font>",
        ["fr"] = "🎁 <font color=\"#ff8c00\">Get 3 Days FREE Premium!</font>",
        ["de"] = "🎁 <font color=\"#ff8c00\">Get 3 Days FREE Premium!</font>",
        ["pt"] = "🎁 <font color=\"#ff8c00\">Get 3 Days FREE Premium!</font>",
    },
    ["Teleport to Sheriff"] = {
        ["en"] = "Teleport to Sheriff",
        ["ar"] = "انتقال للشرطي",
        ["ru"] = "Teleport to Sheriff",
        ["tr"] = "Teleport to Sheriff",
        ["es"] = "Teleport to Sheriff",
        ["fr"] = "Teleport to Sheriff",
        ["de"] = "Teleport to Sheriff",
        ["pt"] = "Teleport to Sheriff",
    },
    ["Sheriff not found or not alive!"] = {
        ["en"] = "Sheriff not found or not alive!",
        ["ar"] = "الشرطي غير موجود أو ليس على قيد الحياة!",
        ["ru"] = "Sheriff not found or not alive!",
        ["tr"] = "Sheriff not found or not alive!",
        ["es"] = "Sheriff not found or not alive!",
        ["fr"] = "Sheriff not found or not alive!",
        ["de"] = "Sheriff not found or not alive!",
        ["pt"] = "Sheriff not found or not alive!",
    },
    ["Telegram channel link copied to clipboard"] = {
        ["en"] = "Telegram channel link copied to clipboard",
        ["ar"] = "تم نسخ رابط قناة التليجرام إلى الحافظة!",
        ["ru"] = "Telegram channel link copied to clipboard",
        ["tr"] = "Telegram channel link copied to clipboard",
        ["es"] = "Telegram channel link copied to clipboard",
        ["fr"] = "Telegram channel link copied to clipboard",
        ["de"] = "Telegram channel link copied to clipboard",
        ["pt"] = "Telegram channel link copied to clipboard",
    },
    ["Join our community for updates, announcements, and key claims!"] = {
        ["en"] = "Join our community for updates, announcements, and key claims!",
        ["ar"] = "انضم إلى مجتمعنا للحصول على التحديثات والإعلانات والمطالبة بالمفاتيح!",
        ["ru"] = "Join our community for updates, announcements, and key claims!",
        ["tr"] = "Join our community for updates, announcements, and key claims!",
        ["es"] = "Join our community for updates, announcements, and key claims!",
        ["fr"] = "Join our community for updates, announcements, and key claims!",
        ["de"] = "Join our community for updates, announcements, and key claims!",
        ["pt"] = "Join our community for updates, announcements, and key claims!",
    },
    ["Auto Kill"] = {
        ["en"] = "Auto Kill",
        ["ar"] = "القتل التلقائي",
        ["ru"] = "Auto Kill",
        ["tr"] = "Auto Kill",
        ["es"] = "Auto Kill",
        ["fr"] = "Auto Kill",
        ["de"] = "Auto Kill",
        ["pt"] = "Auto Kill",
    },
    ["You need a Gun!"] = {
        ["en"] = "You need a Gun!",
        ["ar"] = "تحتاج إلى مسدس!",
        ["ru"] = "You need a Gun!",
        ["tr"] = "You need a Gun!",
        ["es"] = "You need a Gun!",
        ["fr"] = "You need a Gun!",
        ["de"] = "You need a Gun!",
        ["pt"] = "You need a Gun!",
    },
    ["Performance"] = {
        ["en"] = "Performance",
        ["ar"] = "الأداء واللاق",
        ["ru"] = "Performance",
        ["tr"] = "Performance",
        ["es"] = "Performance",
        ["fr"] = "Performance",
        ["de"] = "Performance",
        ["pt"] = "Performance",
    },
    ["Textures deleted! FPS Boosted."] = {
        ["en"] = "Textures deleted! FPS Boosted.",
        ["ar"] = "تم حذف الخامات لتخفيف اللاق!",
        ["ru"] = "Textures deleted! FPS Boosted.",
        ["tr"] = "Textures deleted! FPS Boosted.",
        ["es"] = "Textures deleted! FPS Boosted.",
        ["fr"] = "Textures deleted! FPS Boosted.",
        ["de"] = "Textures deleted! FPS Boosted.",
        ["pt"] = "Textures deleted! FPS Boosted.",
    },
    ["Disable Shadows & Fog"] = {
        ["en"] = "Disable Shadows & Fog",
        ["ar"] = "إيقاف الظلال والضباب",
        ["ru"] = "Disable Shadows & Fog",
        ["tr"] = "Disable Shadows & Fog",
        ["es"] = "Disable Shadows & Fog",
        ["fr"] = "Disable Shadows & Fog",
        ["de"] = "Disable Shadows & Fog",
        ["pt"] = "Disable Shadows & Fog",
    },
    ["Mod"] = {
        ["en"] = "Mod",
        ["ar"] = "التعديلات",
        ["ru"] = "Mod",
        ["tr"] = "Mod",
        ["es"] = "Mod",
        ["fr"] = "Mod",
        ["de"] = "Mod",
        ["pt"] = "Mod",
    },
    ["Faster Kill Murder Button"] = {
        ["en"] = "Faster Kill Murder Button",
        ["ar"] = "زر القتل السريع للماردر",
        ["ru"] = "Faster Kill Murder Button",
        ["tr"] = "Faster Kill Murder Button",
        ["es"] = "Faster Kill Murder Button",
        ["fr"] = "Faster Kill Murder Button",
        ["de"] = "Faster Kill Murder Button",
        ["pt"] = "Faster Kill Murder Button",
    },
    ["Player Jump Power"] = {
        ["en"] = "Player Jump Power",
        ["ar"] = "قوة قفز اللاعب",
        ["ru"] = "Player Jump Power",
        ["tr"] = "Player Jump Power",
        ["es"] = "Player Jump Power",
        ["fr"] = "Player Jump Power",
        ["de"] = "Player Jump Power",
        ["pt"] = "Player Jump Power",
    },
    ["Fling Sheriff"] = {
        ["en"] = "Fling Sheriff",
        ["ar"] = "تفجير الشرطي",
        ["ru"] = "Fling Sheriff",
        ["tr"] = "Fling Sheriff",
        ["es"] = "Fling Sheriff",
        ["fr"] = "Fling Sheriff",
        ["de"] = "Fling Sheriff",
        ["pt"] = "Fling Sheriff",
    },
    ["YouTube channel link copied to clipboard"] = {
        ["en"] = "YouTube channel link copied to clipboard",
        ["ar"] = "تم نسخ رابط قناة اليوتيوب إلى الحافظة!",
        ["ru"] = "YouTube channel link copied to clipboard",
        ["tr"] = "YouTube channel link copied to clipboard",
        ["es"] = "YouTube channel link copied to clipboard",
        ["fr"] = "YouTube channel link copied to clipboard",
        ["de"] = "YouTube channel link copied to clipboard",
        ["pt"] = "YouTube channel link copied to clipboard",
    },
    ["Auto Kill Murder Mode"] = {
        ["en"] = "Auto Kill Murder Mode",
        ["ar"] = "طريقة قتل القاتل",
        ["ru"] = "Auto Kill Murder Mode",
        ["tr"] = "Auto Kill Murder Mode",
        ["es"] = "Auto Kill Murder Mode",
        ["fr"] = "Auto Kill Murder Mode",
        ["de"] = "Auto Kill Murder Mode",
        ["pt"] = "Auto Kill Murder Mode",
    },
    ["Selected player not found or not alive!"] = {
        ["en"] = "Selected player not found or not alive!",
        ["ar"] = "اللاعب المحدد غير موجود أو ليس على قيد الحياة!",
        ["ru"] = "Selected player not found or not alive!",
        ["tr"] = "Selected player not found or not alive!",
        ["es"] = "Selected player not found or not alive!",
        ["fr"] = "Selected player not found or not alive!",
        ["de"] = "Selected player not found or not alive!",
        ["pt"] = "Selected player not found or not alive!",
    },
    ["Setting"] = {
        ["en"] = "Setting",
        ["ar"] = "الإعدادات",
        ["ru"] = "Setting",
        ["tr"] = "Setting",
        ["es"] = "Setting",
        ["fr"] = "Setting",
        ["de"] = "Setting",
        ["pt"] = "Setting",
    },
    ["Key Active"] = {
        ["en"] = "Key Active",
        ["ar"] = "المفتاح نشط",
        ["ru"] = "Key Active",
        ["tr"] = "Key Active",
        ["es"] = "Key Active",
        ["fr"] = "Key Active",
        ["de"] = "Key Active",
        ["pt"] = "Key Active",
    },
    ["Error"] = {
        ["en"] = "Error",
        ["ar"] = "خطأ",
        ["ru"] = "Error",
        ["tr"] = "Error",
        ["es"] = "Error",
        ["fr"] = "Error",
        ["de"] = "Error",
        ["pt"] = "Error",
    },
    ["Smooth Plastic World"] = {
        ["en"] = "Smooth Plastic World",
        ["ar"] = "العالم بلاستيك ناعم",
        ["ru"] = "Smooth Plastic World",
        ["tr"] = "Smooth Plastic World",
        ["es"] = "Smooth Plastic World",
        ["fr"] = "Smooth Plastic World",
        ["de"] = "Smooth Plastic World",
        ["pt"] = "Smooth Plastic World",
    },
    ["Key Deactivated"] = {
        ["en"] = "Key Deactivated",
        ["ar"] = "تم إلغاء تفعيل المفتاح",
        ["ru"] = "Key Deactivated",
        ["tr"] = "Key Deactivated",
        ["es"] = "Key Deactivated",
        ["fr"] = "Key Deactivated",
        ["de"] = "Key Deactivated",
        ["pt"] = "Key Deactivated",
    },
    ["Teleported to Active Map!"] = {
        ["en"] = "Teleported to Active Map!",
        ["ar"] = "تم الانتقال إلى الخريطة النشطة!",
        ["ru"] = "Teleported to Active Map!",
        ["tr"] = "Teleported to Active Map!",
        ["es"] = "Teleported to Active Map!",
        ["fr"] = "Teleported to Active Map!",
        ["de"] = "Teleported to Active Map!",
        ["pt"] = "Teleported to Active Map!",
    },
    ["You need a Knife to use Kill All!"] = {
        ["en"] = "You need a Knife to use Kill All!",
        ["ar"] = "تحتاج إلى سكين لاستخدام ميزة قتل الجميع!",
        ["ru"] = "You need a Knife to use Kill All!",
        ["tr"] = "You need a Knife to use Kill All!",
        ["es"] = "You need a Knife to use Kill All!",
        ["fr"] = "You need a Knife to use Kill All!",
        ["de"] = "You need a Knife to use Kill All!",
        ["pt"] = "You need a Knife to use Kill All!",
    },
    ["Fly Speed"] = {
        ["en"] = "Fly Speed",
        ["ar"] = "سرعة الطيران",
        ["ru"] = "Fly Speed",
        ["tr"] = "Fly Speed",
        ["es"] = "Fly Speed",
        ["fr"] = "Fly Speed",
        ["de"] = "Fly Speed",
        ["pt"] = "Fly Speed",
    },
    ["Join our Discord to claim your FREE key and disable ads! Visit www.sphub.lol"] = {
        ["en"] = "Join our Discord to claim your FREE key and disable ads! Visit www.sphub.lol",
        ["ar"] = "انضم لـ Discord للحصول على مفتاح مجاني وإيقاف الإعلانات! زر موقعنا www.sphub.lol",
        ["ru"] = "Join our Discord to claim your FREE key and disable ads! Visit www.sphub.lol",
        ["tr"] = "Join our Discord to claim your FREE key and disable ads! Visit www.sphub.lol",
        ["es"] = "Join our Discord to claim your FREE key and disable ads! Visit www.sphub.lol",
        ["fr"] = "Join our Discord to claim your FREE key and disable ads! Visit www.sphub.lol",
        ["de"] = "Join our Discord to claim your FREE key and disable ads! Visit www.sphub.lol",
        ["pt"] = "Join our Discord to claim your FREE key and disable ads! Visit www.sphub.lol",
    },
    ["Dropped Gun"] = {
        ["en"] = "Dropped Gun",
        ["ar"] = "سلاح ساقط",
        ["ru"] = "Dropped Gun",
        ["tr"] = "Dropped Gun",
        ["es"] = "Dropped Gun",
        ["fr"] = "Dropped Gun",
        ["de"] = "Dropped Gun",
        ["pt"] = "Dropped Gun",
    },
    ["Premium deactivated and key cleared"] = {
        ["en"] = "Premium deactivated and key cleared",
        ["ar"] = "تم إلغاء تفعيل البريميوم ومسح المفتاح",
        ["ru"] = "Premium deactivated and key cleared",
        ["tr"] = "Premium deactivated and key cleared",
        ["es"] = "Premium deactivated and key cleared",
        ["fr"] = "Premium deactivated and key cleared",
        ["de"] = "Premium deactivated and key cleared",
        ["pt"] = "Premium deactivated and key cleared",
    },
    ["SP Hub Premium"] = {
        ["en"] = "SP Hub Premium",
        ["ar"] = "SP Hub بريميوم",
        ["ru"] = "SP Hub Premium",
        ["tr"] = "SP Hub Premium",
        ["es"] = "SP Hub Premium",
        ["fr"] = "SP Hub Premium",
        ["de"] = "SP Hub Premium",
        ["pt"] = "SP Hub Premium",
    },
    ["Get Key"] = {
        ["en"] = "Get Key",
        ["ar"] = "الحصول على المفتاح",
        ["ru"] = "Get Key",
        ["tr"] = "Get Key",
        ["es"] = "Get Key",
        ["fr"] = "Get Key",
        ["de"] = "Get Key",
        ["pt"] = "Get Key",
    },
    ["Sheriff Tracer"] = {
        ["en"] = "Sheriff Tracer",
        ["ar"] = "خطوط كاشف الشرطي",
        ["ru"] = "Sheriff Tracer",
        ["tr"] = "Sheriff Tracer",
        ["es"] = "Sheriff Tracer",
        ["fr"] = "Sheriff Tracer",
        ["de"] = "Sheriff Tracer",
        ["pt"] = "Sheriff Tracer",
    },
    ["Fling Player"] = {
        ["en"] = "Fling Player",
        ["ar"] = "طيران وتفجير لاعب",
        ["ru"] = "Fling Player",
        ["tr"] = "Fling Player",
        ["es"] = "Fling Player",
        ["fr"] = "Fling Player",
        ["de"] = "Fling Player",
        ["pt"] = "Fling Player",
    },
    ["Protection"] = {
        ["en"] = "Protection",
        ["ar"] = "الحماية",
        ["ru"] = "Protection",
        ["tr"] = "Protection",
        ["es"] = "Protection",
        ["fr"] = "Protection",
        ["de"] = "Protection",
        ["pt"] = "Protection",
    },
    ["Player Teleport"] = {
        ["en"] = "Player Teleport",
        ["ar"] = "انتقال اللاعبين",
        ["ru"] = "Player Teleport",
        ["tr"] = "Player Teleport",
        ["es"] = "Player Teleport",
        ["fr"] = "Player Teleport",
        ["de"] = "Player Teleport",
        ["pt"] = "Player Teleport",
    },
    ["You need a Knife to use Auto Kill!"] = {
        ["en"] = "You need a Knife to use Auto Kill!",
        ["ar"] = "تحتاج إلى سكين لاستخدام ميزة القتل التلقائي!",
        ["ru"] = "You need a Knife to use Auto Kill!",
        ["tr"] = "You need a Knife to use Auto Kill!",
        ["es"] = "You need a Knife to use Auto Kill!",
        ["fr"] = "You need a Knife to use Auto Kill!",
        ["de"] = "You need a Knife to use Auto Kill!",
        ["pt"] = "You need a Knife to use Auto Kill!",
    },
    ["<font color=\"#ffffff\">To claim it, visit </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, create an account and link it to Discord, and you’ll be given the key </font><font color=\"#ff8c00\"><b>for free!</b></font>"] = {
        ["en"] = "<font color=\"#ffffff\">To claim it, visit </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, create an account and link it to Discord, and you’ll be given the key </font><font color=\"#ff8c00\"><b>for free!</b></font>",
        ["ar"] = "<font color=\"#ffffff\">للمطالبة به، قم بزيارة </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">، وأنشئ حساباً وقم بربطه بالديسكورد، وسيتم إعطاؤك المفتاح </font><font color=\"#ff8c00\"><b>مجانًا!</b></font>",
        ["ru"] = "<font color=\"#ffffff\">To claim it, visit </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, create an account and link it to Discord, and you’ll be given the key </font><font color=\"#ff8c00\"><b>for free!</b></font>",
        ["tr"] = "<font color=\"#ffffff\">To claim it, visit </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, create an account and link it to Discord, and you’ll be given the key </font><font color=\"#ff8c00\"><b>for free!</b></font>",
        ["es"] = "<font color=\"#ffffff\">To claim it, visit </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, create an account and link it to Discord, and you’ll be given the key </font><font color=\"#ff8c00\"><b>for free!</b></font>",
        ["fr"] = "<font color=\"#ffffff\">To claim it, visit </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, create an account and link it to Discord, and you’ll be given the key </font><font color=\"#ff8c00\"><b>for free!</b></font>",
        ["de"] = "<font color=\"#ffffff\">To claim it, visit </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, create an account and link it to Discord, and you’ll be given the key </font><font color=\"#ff8c00\"><b>for free!</b></font>",
        ["pt"] = "<font color=\"#ffffff\">To claim it, visit </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, create an account and link it to Discord, and you’ll be given the key </font><font color=\"#ff8c00\"><b>for free!</b></font>",
    },
    ["Auto Collect Coins"] = {
        ["en"] = "Auto Collect Coins",
        ["ar"] = "تجميع العملات تلقائياً",
        ["ru"] = "Auto Collect Coins",
        ["tr"] = "Auto Collect Coins",
        ["es"] = "Auto Collect Coins",
        ["fr"] = "Auto Collect Coins",
        ["de"] = "Auto Collect Coins",
        ["pt"] = "Auto Collect Coins",
    },
    ["Coin Tween Speed"] = {
        ["en"] = "Coin Tween Speed",
        ["ar"] = "سرعة سحب العملات",
        ["ru"] = "Coin Tween Speed",
        ["tr"] = "Coin Tween Speed",
        ["es"] = "Coin Tween Speed",
        ["fr"] = "Coin Tween Speed",
        ["de"] = "Coin Tween Speed",
        ["pt"] = "Coin Tween Speed",
    },
    ["Fling Murderer"] = {
        ["en"] = "Fling Murderer",
        ["ar"] = "تفجير القاتل",
        ["ru"] = "Fling Murderer",
        ["tr"] = "Fling Murderer",
        ["es"] = "Fling Murderer",
        ["fr"] = "Fling Murderer",
        ["de"] = "Fling Murderer",
        ["pt"] = "Fling Murderer",
    },
    ["Fling Touch"] = {
        ["en"] = "Fling Touch",
        ["ar"] = "التفجير عند اللمس",
        ["ru"] = "Fling Touch",
        ["tr"] = "Fling Touch",
        ["es"] = "Fling Touch",
        ["fr"] = "Fling Touch",
        ["de"] = "Fling Touch",
        ["pt"] = "Fling Touch",
    },
    ["Auto Kill All Mode"] = {
        ["en"] = "Auto Kill All Mode",
        ["ar"] = "طريقة قتل الجميع",
        ["ru"] = "Auto Kill All Mode",
        ["tr"] = "Auto Kill All Mode",
        ["es"] = "Auto Kill All Mode",
        ["fr"] = "Auto Kill All Mode",
        ["de"] = "Auto Kill All Mode",
        ["pt"] = "Auto Kill All Mode",
    },
    ["Fly"] = {
        ["en"] = "Fly",
        ["ar"] = "الطيران",
        ["ru"] = "Fly",
        ["tr"] = "Fly",
        ["es"] = "Fly",
        ["fr"] = "Fly",
        ["de"] = "Fly",
        ["pt"] = "Fly",
    },
    ["Anti Void"] = {
        ["en"] = "Anti Void",
        ["ar"] = "الحماية من السقوط",
        ["ru"] = "Anti Void",
        ["tr"] = "Anti Void",
        ["es"] = "Anti Void",
        ["fr"] = "Anti Void",
        ["de"] = "Anti Void",
        ["pt"] = "Anti Void",
    },
    ["World materials restored!"] = {
        ["en"] = "World materials restored!",
        ["ar"] = "تمت استعادة خامات العالم!",
        ["ru"] = "World materials restored!",
        ["tr"] = "World materials restored!",
        ["es"] = "World materials restored!",
        ["fr"] = "World materials restored!",
        ["de"] = "World materials restored!",
        ["pt"] = "World materials restored!",
    },
    ["SP Hub Channels"] = {
        ["en"] = "SP Hub Channels",
        ["ar"] = "قنوات SP Hub",
        ["ru"] = "SP Hub Channels",
        ["tr"] = "SP Hub Channels",
        ["es"] = "SP Hub Channels",
        ["fr"] = "SP Hub Channels",
        ["de"] = "SP Hub Channels",
        ["pt"] = "SP Hub Channels",
    },
    ["SP Hub"] = {
        ["en"] = "SP Hub",
        ["ar"] = "SP Hub",
        ["ru"] = "SP Hub",
        ["tr"] = "SP Hub",
        ["es"] = "SP Hub",
        ["fr"] = "SP Hub",
        ["de"] = "SP Hub",
        ["pt"] = "SP Hub",
    },
    ["s"] = {
        ["en"] = "s",
        ["ar"] = "ثانية",
        ["ru"] = "s",
        ["tr"] = "s",
        ["es"] = "s",
        ["fr"] = "s",
        ["de"] = "s",
        ["pt"] = "s",
    },
    ["Discord Server"] = {
        ["en"] = "Discord Server",
        ["ar"] = "سيرفر الديسكورد",
        ["ru"] = "Discord Server",
        ["tr"] = "Discord Server",
        ["es"] = "Discord Server",
        ["fr"] = "Discord Server",
        ["de"] = "Discord Server",
        ["pt"] = "Discord Server",
    },
    ["Welcome to SP Hub! Enjoy your first session ad-free!"] = {
        ["en"] = "Welcome to SP Hub! Enjoy your first session ad-free!",
        ["ar"] = "مرحباً بك في SP Hub! استمتع بجلستك الأولى بدون إعلانات!",
        ["ru"] = "Welcome to SP Hub! Enjoy your first session ad-free!",
        ["tr"] = "Welcome to SP Hub! Enjoy your first session ad-free!",
        ["es"] = "Welcome to SP Hub! Enjoy your first session ad-free!",
        ["fr"] = "Welcome to SP Hub! Enjoy your first session ad-free!",
        ["de"] = "Welcome to SP Hub! Enjoy your first session ad-free!",
        ["pt"] = "Welcome to SP Hub! Enjoy your first session ad-free!",
    },
    ["Key link copied"] = {
        ["en"] = "Key link copied",
        ["ar"] = "تم نسخ رابط المفتاح",
        ["ru"] = "Key link copied",
        ["tr"] = "Key link copied",
        ["es"] = "Key link copied",
        ["fr"] = "Key link copied",
        ["de"] = "Key link copied",
        ["pt"] = "Key link copied",
    },
    ["No active game map found in workspace.Normal!"] = {
        ["en"] = "No active game map found in workspace.Normal!",
        ["ar"] = "لم يتم العثور على خريطة نشطة في workspace.Normal!",
        ["ru"] = "No active game map found in workspace.Normal!",
        ["tr"] = "No active game map found in workspace.Normal!",
        ["es"] = "No active game map found in workspace.Normal!",
        ["fr"] = "No active game map found in workspace.Normal!",
        ["de"] = "No active game map found in workspace.Normal!",
        ["pt"] = "No active game map found in workspace.Normal!",
    },
    ["Teleports"] = {
        ["en"] = "Teleports",
        ["ar"] = "الانتقالات",
        ["ru"] = "Teleports",
        ["tr"] = "Teleports",
        ["es"] = "Teleports",
        ["fr"] = "Teleports",
        ["de"] = "Teleports",
        ["pt"] = "Teleports",
    },
    ["JumpPower"] = {
        ["en"] = "JumpPower",
        ["ar"] = "قوة القفز",
        ["ru"] = "JumpPower",
        ["tr"] = "JumpPower",
        ["es"] = "JumpPower",
        ["fr"] = "JumpPower",
        ["de"] = "JumpPower",
        ["pt"] = "JumpPower",
    },
    ["No alternative servers found!"] = {
        ["en"] = "No alternative servers found!",
        ["ar"] = "لم يتم العثور على سيرفرات بديلة!",
        ["ru"] = "No alternative servers found!",
        ["tr"] = "No alternative servers found!",
        ["es"] = "No alternative servers found!",
        ["fr"] = "No alternative servers found!",
        ["de"] = "No alternative servers found!",
        ["pt"] = "No alternative servers found!",
    },
    ["Server Hop"] = {
        ["en"] = "Server Hop",
        ["ar"] = "الانتقال لسيرفر آخر",
        ["ru"] = "Server Hop",
        ["tr"] = "Server Hop",
        ["es"] = "Server Hop",
        ["fr"] = "Server Hop",
        ["de"] = "Server Hop",
        ["pt"] = "Server Hop",
    },
    ["Murderer not found or not alive!"] = {
        ["en"] = "Murderer not found or not alive!",
        ["ar"] = "القاتل غير موجود أو ليس على قيد الحياة!",
        ["ru"] = "Murderer not found or not alive!",
        ["tr"] = "Murderer not found or not alive!",
        ["es"] = "Murderer not found or not alive!",
        ["fr"] = "Murderer not found or not alive!",
        ["de"] = "Murderer not found or not alive!",
        ["pt"] = "Murderer not found or not alive!",
    },
    ["Autofarm"] = {
        ["en"] = "Autofarm",
        ["ar"] = "التجميع التلقائي",
        ["ru"] = "Autofarm",
        ["tr"] = "Autofarm",
        ["es"] = "Autofarm",
        ["fr"] = "Autofarm",
        ["de"] = "Autofarm",
        ["pt"] = "Autofarm",
    },
    ["Telegram Channel"] = {
        ["en"] = "Telegram Channel",
        ["ar"] = "قناة التليجرام",
        ["ru"] = "Telegram Channel",
        ["tr"] = "Telegram Channel",
        ["es"] = "Telegram Channel",
        ["fr"] = "Telegram Channel",
        ["de"] = "Telegram Channel",
        ["pt"] = "Telegram Channel",
    },
    ["Your coin bag is full! Autofarm paused."] = {
        ["en"] = "Your coin bag is full! Autofarm paused.",
        ["ar"] = "حقيبة العملات ممتلئة! تم إيقاف التجميع تلقائياً.",
        ["ru"] = "Your coin bag is full! Autofarm paused.",
        ["tr"] = "Your coin bag is full! Autofarm paused.",
        ["es"] = "Your coin bag is full! Autofarm paused.",
        ["fr"] = "Your coin bag is full! Autofarm paused.",
        ["de"] = "Your coin bag is full! Autofarm paused.",
        ["pt"] = "Your coin bag is full! Autofarm paused.",
    },
    ["✅ Auto Login"] = {
        ["en"] = "✅ Auto Login",
        ["ar"] = "✅ تسجيل الدخول التلقائي",
        ["ru"] = "✅ Auto Login",
        ["tr"] = "✅ Auto Login",
        ["es"] = "✅ Auto Login",
        ["fr"] = "✅ Auto Login",
        ["de"] = "✅ Auto Login",
        ["pt"] = "✅ Auto Login",
    },
    ["Copied"] = {
        ["en"] = "Copied",
        ["ar"] = "تم النسخ",
        ["ru"] = "Copied",
        ["tr"] = "Copied",
        ["es"] = "Copied",
        ["fr"] = "Copied",
        ["de"] = "Copied",
        ["pt"] = "Copied",
    },
    ["Enter key first"] = {
        ["en"] = "Enter key first",
        ["ar"] = "أدخل المفتاح أولاً",
        ["ru"] = "Enter key first",
        ["tr"] = "Enter key first",
        ["es"] = "Enter key first",
        ["fr"] = "Enter key first",
        ["de"] = "Enter key first",
        ["pt"] = "Enter key first",
    },
    ["A gun has dropped on the map!"] = {
        ["en"] = "A gun has dropped on the map!",
        ["ar"] = "سقط مسدس على الخريطة!",
        ["ru"] = "A gun has dropped on the map!",
        ["tr"] = "A gun has dropped on the map!",
        ["es"] = "A gun has dropped on the map!",
        ["fr"] = "A gun has dropped on the map!",
        ["de"] = "A gun has dropped on the map!",
        ["pt"] = "A gun has dropped on the map!",
    },
    ["Website URL copied to clipboard"] = {
        ["en"] = "Website URL copied to clipboard",
        ["ar"] = "تم نسخ رابط الموقع للحافظة",
        ["ru"] = "Website URL copied to clipboard",
        ["tr"] = "Website URL copied to clipboard",
        ["es"] = "Website URL copied to clipboard",
        ["fr"] = "Website URL copied to clipboard",
        ["de"] = "Website URL copied to clipboard",
        ["pt"] = "Website URL copied to clipboard",
    },
    ["Player Speed"] = {
        ["en"] = "Player Speed",
        ["ar"] = "سرعة اللاعب",
        ["ru"] = "Player Speed",
        ["tr"] = "Player Speed",
        ["es"] = "Player Speed",
        ["fr"] = "Player Speed",
        ["de"] = "Player Speed",
        ["pt"] = "Player Speed",
    },
    ["Successfully eliminated all players safely!"] = {
        ["en"] = "Successfully eliminated all players safely!",
        ["ar"] = "تم التخلص من جميع اللاعبين بأمان!",
        ["ru"] = "Successfully eliminated all players safely!",
        ["tr"] = "Successfully eliminated all players safely!",
        ["es"] = "Successfully eliminated all players safely!",
        ["fr"] = "Successfully eliminated all players safely!",
        ["de"] = "Successfully eliminated all players safely!",
        ["pt"] = "Successfully eliminated all players safely!",
    },
    ["Rejoin Server"] = {
        ["en"] = "Rejoin Server",
        ["ar"] = "إعادة دخول السيرفر",
        ["ru"] = "Rejoin Server",
        ["tr"] = "Rejoin Server",
        ["es"] = "Rejoin Server",
        ["fr"] = "Rejoin Server",
        ["de"] = "Rejoin Server",
        ["pt"] = "Rejoin Server",
    },
    ["Time Left"] = {
        ["en"] = "Time Left",
        ["ar"] = "الوقت المتبقي",
        ["ru"] = "Time Left",
        ["tr"] = "Time Left",
        ["es"] = "Time Left",
        ["fr"] = "Time Left",
        ["de"] = "Time Left",
        ["pt"] = "Time Left",
    },
    ["Auto Kill Murder"] = {
        ["en"] = "Auto Kill Murder",
        ["ar"] = "القتل التلقائي للقاتل",
        ["ru"] = "Auto Kill Murder",
        ["tr"] = "Auto Kill Murder",
        ["es"] = "Auto Kill Murder",
        ["fr"] = "Auto Kill Murder",
        ["de"] = "Auto Kill Murder",
        ["pt"] = "Auto Kill Murder",
    },
    ["Anti Fling"] = {
        ["en"] = "Anti Fling",
        ["ar"] = "حماية من التفجير",
        ["ru"] = "Anti Fling",
        ["tr"] = "Anti Fling",
        ["es"] = "Anti Fling",
        ["fr"] = "Anti Fling",
        ["de"] = "Anti Fling",
        ["pt"] = "Anti Fling",
    },
    ["Teleport to Murderer"] = {
        ["en"] = "Teleport to Murderer",
        ["ar"] = "انتقال للقاتل",
        ["ru"] = "Teleport to Murderer",
        ["tr"] = "Teleport to Murderer",
        ["es"] = "Teleport to Murderer",
        ["fr"] = "Teleport to Murderer",
        ["de"] = "Teleport to Murderer",
        ["pt"] = "Teleport to Murderer",
    },
    ["Murderer"] = {
        ["en"] = "Murderer",
        ["ar"] = "القاتل",
        ["ru"] = "Murderer",
        ["tr"] = "Murderer",
        ["es"] = "Murderer",
        ["fr"] = "Murderer",
        ["de"] = "Murderer",
        ["pt"] = "Murderer",
    },
    ["Fling Target Player"] = {
        ["en"] = "Fling Target Player",
        ["ar"] = "تفجير لاعب محدد",
        ["ru"] = "Fling Target Player",
        ["tr"] = "Fling Target Player",
        ["es"] = "Fling Target Player",
        ["fr"] = "Fling Target Player",
        ["de"] = "Fling Target Player",
        ["pt"] = "Fling Target Player",
    },
    ["🎁 <font color=\"#ff8c00\">Get 3 Days FREE Premium!</font>"] = {
        en = "🎁 <font color=\"#ff8c00\">Get 3 Days FREE Premium!</font>",
        ar = "🎁 <font color=\"#ff8c00\">احصل على 3 أيام بريميوم مجاناً!</font>",
        ru = "🎁 <font color=\"#ff8c00\">Получите 3 дня БЕСПЛАТНОГО премиума!</font>",
        tr = "🎁 <font color=\"#ff8c00\">3 Günlük ÜCRETSİZ Premium Alın!</font>",
        es = "🎁 <font color=\"#ff8c00\">¡Obtén 3 días de Premium GRATIS!</font>",
        fr = "🎁 <font color=\"#ff8c00\">Obtenez 3 jours de Premium GRATUIT !</font>",
        de = "🎁 <font color=\"#ff8c00\">Erhalten Sie 3 Tage KOSTENLOSES Premium!</font>",
        pt = "🎁 <font color=\"#ff8c00\">Ganhe 3 dias de Premium GRATUITO!</font>",
    },
    ["<font color=\"#ffffff\">To claim it, visit </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, create an account and link it to Discord, and you'll be given the key </font><font color=\"#ff8c00\"><b>for free!</b></font>"] = {
        en = "<font color=\"#ffffff\">To claim it, visit </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, create an account and link it to Discord, and you'll be given the key </font><font color=\"#ff8c00\"><b>for free!</b></font>",
        ar = "<font color=\"#ffffff\">للحصول عليها، قم بزيارة </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">، وأنشئ حساباً واربطه بالديسكورد، وسيتم إعطاؤك المفتاح </font><font color=\"#ff8c00\"><b>مجانًا!</b></font>",
        ru = "<font color=\"#ffffff\">Чтобы получить его, посетите </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, создайте аккаунт и свяжите его с Discord, и вам дадут ключ </font><font color=\"#ff8c00\"><b>бесплатно!</b></font>",
        tr = "<font color=\"#ffffff\">Talep etmek için </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\"> adresini ziyaret edin, bir hesap oluşturun ve Discord'a bağlayın, anahtar size </font><font color=\"#ff8c00\"><b>ücretsiz verilecektir!</b></font>",
        es = "<font color=\"#ffffff\">Para reclamarlo, visite </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, cree una cuenta y vincúlela a Discord, y se le dará la clave </font><font color=\"#ff8c00\"><b>¡gratis!</b></font>",
        fr = "<font color=\"#ffffff\">Pour le réclamer, visitez </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, créez un compte et liez-le à Discord, et la clé vous sera donnée </font><font color=\"#ff8c00\"><b>gratuitement !</b></font>",
        de = "<font color=\"#ffffff\">Um es einzufordern, besuchen Sie </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, erstellen Sie ein Konto und verknüpfen Sie es mit Discord. Der Schlüssel wird Ihnen </font><font color=\"#ff8c00\"><b>kostenlos zur Verfügung gestellt!</b></font>",
        pt = "<font color=\"#ffffff\">Para resgatá-lo, visite </font><font color=\"#1e90ff\"><b>www.sphub.lol</b></font><font color=\"#ffffff\">, crie uma conta e vincule-a ao Discord, e você receberá a chave </font><font color=\"#ff8c00\"><b>de graça!</b></font>",
    },
    ["Select ESP Players"] = {
        ["en"] = "Select ESP Players",
        ["ar"] = "تحديد اللاعبين للـ ESP",
        ["ru"] = "Выбрать игроков для ESP",
        ["tr"] = "ESP Oyuncularını Seç",
        ["es"] = "Seleccionar jugadores ESP",
        ["fr"] = "Sélectionner les joueurs ESP",
        ["de"] = "ESP-Spieler auswählen",
        ["pt"] = "Selecionar jogadores ESP",
    },
    ["Innocent"] = {
        ["en"] = "Innocent",
        ["ar"] = "بريء",
        ["ru"] = "Мирный",
        ["tr"] = "Masum",
        ["es"] = "Inocente",
        ["fr"] = "Innocent",
        ["de"] = "Unschuldig",
        ["pt"] = "Inocente",
    },
    ["Select Tracers Players"] = {
        ["en"] = "Select Tracers Players",
        ["ar"] = "تحديد خطوط اللاعبين للـ Tracers",
        ["ru"] = "Выбрать игроков для трассировки",
        ["tr"] = "Tracer Oyuncularını Seç",
        ["es"] = "Seleccionar jugadores de trazadores",
        ["fr"] = "Sélectionner les traceurs de joueurs",
        ["de"] = "Tracer-Spieler auswählen",
        ["pt"] = "Selecionar jogadores de traçadores",
    }
,
    ["Bring Everyone"] = {
        ["en"] = "Bring Everyone",
        ["ar"] = "سحب الجميع إليك",
        ["ru"] = "Притянуть всех",
        ["tr"] = "Herkesi Getir",
        ["es"] = "Traer a Todos",
        ["fr"] = "Amener Tout le Monde",
        ["de"] = "Alle Bringen",
        ["pt"] = "Trazer Todos",
    },
    ["Default Fov"] = {
        ["en"] = "Default FOV",
        ["ar"] = "مجال الرؤية الافتراضي",
        ["ru"] = "FOV по умолчанию",
        ["tr"] = "Varsayılan FOV",
        ["es"] = "FOV por Defecto",
        ["fr"] = "FOV par Défaut",
        ["de"] = "Standard-FOV",
        ["pt"] = "FOV Padrão",
    },
    ["ESP X-Ray"] = {
        ["en"] = "ESP X-Ray",
        ["ar"] = "كاشف الجدران (X-Ray)",
        ["ru"] = "Рентген ESP (X-Ray)",
        ["tr"] = "ESP X-Ray",
        ["es"] = "ESP Rayos X",
        ["fr"] = "ESP X-Ray",
        ["de"] = "ESP X-Ray",
        ["pt"] = "ESP Raio-X",
    },
    ["Fov Changer"] = {
        ["en"] = "FOV Changer",
        ["ar"] = "معدل مجال الرؤية",
        ["ru"] = "Изменение FOV",
        ["tr"] = "FOV Değiştirici",
        ["es"] = "Cambiador de FOV",
        ["fr"] = "Modificateur de FOV",
        ["de"] = "FOV-Änderer",
        ["pt"] = "Alterador de FOV",
    },
    ["Infinite Jump"] = {
        ["en"] = "Infinite Jump",
        ["ar"] = "قفز لانهائي",
        ["ru"] = "Бесконечный прыжок",
        ["tr"] = "Sonsuz Zıplama",
        ["es"] = "Salto Infinito",
        ["fr"] = "Saut Infini",
        ["de"] = "Unendlicher Sprung",
        ["pt"] = "Pulo Infinito",
    },
    ["Lifetime"] = {
        ["en"] = "Lifetime",
        ["ar"] = "مدى الحياة",
        ["ru"] = "Навсегда",
        ["tr"] = "Ömür Boyu",
        ["es"] = "De por Vida",
        ["fr"] = "À Vie",
        ["de"] = "Lebenslang",
        ["pt"] = "Vitalício",
    },
    ["Loop detected! Spawned rescue platform locally."] = {
        ["en"] = "Loop detected! Spawned rescue platform locally.",
        ["ar"] = "تم كشف حلقة تكرار! تم إنشاء منصة إنقاذ محلياً.",
        ["ru"] = "Обнаружен цикл! Создана спасательная платформа.",
        ["tr"] = "Döngü tespit edildi! Kurtarma platformu yerel olarak oluşturuldu.",
        ["es"] = "¡Bucle detectado! Plataforma de rescate generada localmente.",
        ["fr"] = "Boucle détectée ! Plateforme de sauvetage générée localement.",
        ["de"] = "Schleife erkannt! Rettungsplattform lokal generiert.",
        ["pt"] = "Loop detectado! Plataforma de resgate criada localmente.",
    },
    ["Shoot Only When Knife Equipped"] = {
        ["en"] = "Shoot Only When Knife Equipped",
        ["ar"] = "إطلاق فقط عندما يمسك القاتل السكين",
        ["ru"] = "Стрелять только когда нож в руке",
        ["tr"] = "Sadece Bıçak Kuşanıldığında Ateş Et",
        ["es"] = "Disparar Solo con Cuchillo Equipado",
        ["fr"] = "Tirer Uniquement avec Couteau Équipé",
        ["de"] = "Nur Schießen wenn Messer ausgerüstet",
        ["pt"] = "Atirar Apenas com Faca Equipada",
    },
    ["Super Lag Reducer"] = {
        ["en"] = "Super Lag Reducer",
        ["ar"] = "مخفض اللاق الخارق",
        ["ru"] = "Супер оптимизатор лагов",
        ["tr"] = "Süper Gecikme Azaltıcı",
        ["es"] = "Súper Reductor de Lag",
        ["fr"] = "Super Réducteur de Lag",
        ["de"] = "Super-Lag-Reduzierer",
        ["pt"] = "Super Redutor de Lag",
    },
    ["Super Lag Reducer Disabled! World restored."] = {
        ["en"] = "Super Lag Reducer Disabled! World restored.",
        ["ar"] = "تم إيقاف مخفض اللاق الخارق! تم استعادة العالم.",
        ["ru"] = "Супер оптимизатор выключен! Мир восстановлен.",
        ["tr"] = "Süper Gecikme Azaltıcı Devre Dışı! Dünya geri yüklendi.",
        ["es"] = "¡Súper Reductor de Lag Desactivado! Mundo restaurado.",
        ["fr"] = "Super Réducteur de Lag Désactivé ! Monde restauré.",
        ["de"] = "Super-Lag-Reduzierer deaktiviert! Welt wiederhergestellt.",
        ["pt"] = "Super Redutor de Lag Desativado! Mundo restaurado.",
    },
    ["Super Lag Reducer Enabled! World optimized."] = {
        ["en"] = "Super Lag Reducer Enabled! World optimized.",
        ["ar"] = "تم تفعيل مخفض اللاق الخارق! تم تحسين العالم.",
        ["ru"] = "Супер оптимизатор включен! Мир оптимизирован.",
        ["tr"] = "Süper Gecikme Azaltıcı Aktif! Dünya optimize edildi.",
        ["es"] = "¡Súper Reductor de Lag Activado! Mundo optimizado.",
        ["fr"] = "Super Réducteur de Lag Activé ! Monde optimisé.",
        ["de"] = "Super-Lag-Reduzierer aktiviert! Welt optimiert.",
        ["pt"] = "Super Redutor de Lag Ativado! Mundo otimizado.",
    },
    ["There no gun dropped"] = {
        ["en"] = "There no gun dropped",
        ["ar"] = "لا يوجد سلاح ساقط حالياً",
        ["ru"] = "Оружие еще не выпало",
        ["tr"] = "Düşen silah yok",
        ["es"] = "No hay arma caída",
        ["fr"] = "Aucune arme tombée",
        ["de"] = "Keine Waffe fallengelassen",
        ["pt"] = "Nenhuma arma caída",
    }
}
